#
# https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
#
default:
  image: python:3.9
  tags:  [docker]

variables:
  MODULEDIR:      tsdm
  MODULENAME:     tsdm
  TESTDIR:        test
  TWINE_PASSWORD: ${CI_JOB_TOKEN}
  TWINE_USERNAME: gitlab-ci-token
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .pytest_cache
    - .mypy_cache
    - venv/

stages:
  - build
  - analysis
  - test
  - deploy

before_script:  # global before_script is run before each and every job.
  - source venv/bin/activate

################
# STAGE: SETUP #
################

build:
  stage: build
  before_script:
    # make directories
    - mkdir badges
    - mkdir reports
    # python setup
    - python -V
    - pip install --upgrade pip virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip pybadges
  script:
    # generate distribution
    - pip install --upgrade wheel setuptools
    - python setup.py sdist bdist_wheel
    # install dependencies
    - pip install --upgrade -r requirements.txt
    # build and install package
    - pip install dist/*.whl
    - pip list
  after_script:
    - source venv/bin/activate
    - > # generate python version badge
      python -m pybadges
      --left-text="python"
      --right-text="3.9"
      --whole-link="https://www.python.org/"
      --logo="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/python.svg"
      --embed-logo
      > badges/python.svg
    - > # generate package version badge
      python -m pybadges
      --left-text="version"
      --right-text="$(cat "$MODULEDIR/VERSION")"
      > badges/version.svg
  artifacts:
    paths:
      - dist/
      - badges/
      - reports/

###################
# STAGE: ANALYSIS #
###################

pylint:
  # see .pylintrc for configuration
  stage: analysis
  needs: [ "build" ]
  script:
    # install dependencies
    - pip install --upgrade pylint pylint-gitlab
    # generate reports
    - pylint $MODULEDIR 
      --exit-zero 
      --load-plugins=pylint_gitlab 
      --output-format=gitlab-codeclimate
      > reports/codeclimate.json
    # human readable
    - pylint $TESTDIR --exit-zero --output-format=colorized
    - pylint $MODULEDIR --exit-zero --output-format=colorized | tee pylint.log
  after_script:
    - source venv/bin/activate
    - SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.log)
    - >
      COLOR=$(python -c "print({0: 'black', 2:'red', 4:'orange', 6:'yellow', 8:'green'}[int($SCORE-$SCORE%2)])")
    - > # generate pylint badge
      python -m pybadges
      --left-text="PyLint"
      --right-text="$SCORE"
      --right-color=$COLOR
      --whole-link="https://github.com/PyCQA/pylint"
      > badges/pylint.svg
  artifacts:
    reports:
      codequality: reports/codeclimate.json
    paths:
      - badges/

flake8:
  # see .flake8 for configuration
  stage: analysis
  needs: [ "build" ]
  script:
    - pip install --upgrade -r requirements-flake8.txt
    - flake8 $MODULEDIR
    - flake8 $TESTDIR
  after_script:
    - source venv/bin/activate
    - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
    - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
    - > # generate flake8 badge
      python -m pybadges
      --left-text="flake8"
      --right-text="$TEXT"
      --right-color="$COLOR"
      --whole-link="https://flake8.pycqa.org/en/latest/"
      > badges/flake8.svg
    - > # generate black code style badge
      python -m pybadges
      --left-text="code style"
      --right-text="black"
      --right-color="black"
      --whole-link="https://github.com/psf/black"
      > badges/black.svg
  artifacts:
    paths:
      - badges/

mypy:
  # see .mpypy.ini for configuration
  stage: analysis
  needs: [ "build" ]
  script:
    - pip install --upgrade mypy
    - mypy $MODULEDIR --install-types --non-interactive  --junit-xml reports/mypy.xml
    - mypy $TESTDIR --install-types --non-interactive  --junit-xml reports/mypy_test.xml
  after_script:
    - source venv/bin/activate
    - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
    - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
    - > # generate mypy badge
      python -m pybadges
      --left-text="MyPy"
      --right-text="$TEXT"
      --right-color="$COLOR"
      --whole-link="https://github.com/python/mypy"
      > badges/mypy.svg
    # --logo="http://mypy-lang.org/static/mypy_light.svg"
    # --embed-logo
  artifacts:
    reports:
      junit: reports/mypy*.xml
    paths:
      - badges/

###############
# STAGE: TEST #
###############

pytest:
  # see pytest.ini for configuration
  stage: test
  needs: [ "build" ]
  script:
    - pip install --upgrade pytest pytest-cov
    - pytest --junitxml=reports/pytest.xml --cov=$MODULEDIR $TESTDIR
    - coverage xml -o reports/coverage.xml
    - coverage report
  after_script:
    - source venv/bin/activate
    - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
    - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
    - > # generate pytest badge
      python -m pybadges
      --left-text="pytest"
      --right-text="$TEXT"
      --right-color="$COLOR"
      --whole-link="https://pytest.org"
      > badges/pytest.svg
    # --logo="https://raw.githubusercontent.com/pytest-dev/pytest/main/doc/en/img/pytest_logo_curves.svg"
    # --embed-logo
  artifacts:
    # https://software.ismll.uni-hildesheim.de/help/ci/unit_test_reports
    reports:
      cobertura: reports/coverage.xml
      junit: reports/pytest.xml
    paths:
      - badges/

#################
# STAGE: DEPLOY #
#################

pypi:
  # https://docs.gitlab.com/ee/user/packages/pypi_repository/
  stage: deploy
  needs: [ "build" ]
  only: [ master ]
  allow_failure: true
  script:
    - pip install --upgrade twine
    - twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  after_script:
    - source venv/bin/activate
    - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
    - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
    - > # generate pypi badge
      python -m pybadges
      --left-text="PyPI"
      --right-text="$TEXT"
      --right-color="$COLOR"
      --whole-link="https://pypi.org/"
      > badges/pypi.svg
    # --logo="http://mypy-lang.org/static/mypy_light.svg"
    # --embed-logo
  artifacts:
    paths:
      - badges/

pages:
  # https://docs.gitlab.com/ee/user/packages/pypi_repository/
  stage: deploy
  needs: [ "build" ]
  only: [ master ]
  allow_failure: true
  script:
    - pip install --upgrade sphinx sphinx-rtd-theme sphinx-math-dollar
    - cd docs
    - make clean
    - sphinx-build -b html . _build
    - mv  _build ../public/
  after_script:
    - source venv/bin/activate
    - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
    - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
    - > # generate sphinx badge
      python -m pybadges
      --left-text="docs"
      --right-text="$TEXT"
      --right-color="$COLOR"
      --whole-link="https://www.sphinx-doc.org"
      > badges/sphinx.svg
    # --logo="https://github.com/sphinx-doc/sphinx/blob/master/doc/_static/favicon.svg"
    # --embed-logo
  artifacts:
    paths:
      - public/
      - badges/
