image: fkrull/multi-python

setup:
  script:
  - apt install python3-pip
  - pip3 install tox

test:
  script:
    tox --recreate

run:
  script:
  - python3 setup.py bdist_wheel
  artifacts:
    paths:
    - dist/*.whl

pages:
  stage: deploy
  script:
    - pip3 install -U sphinx sphinx-rtd-theme numpydoc
    - cd docs ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
