#
# https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
#
default:
  image: python:3.9
  tags:  [docker]

variables:
  MODULEDIR:      tsdm
  TESTDIR:        test
  TWINE_PASSWORD: ${CI_JOB_TOKEN}
  TWINE_USERNAME: gitlab-ci-token
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .pytest_cache
    - .mypy_cache
    - venv/

stages:
  - build
  - analysis
  - test
  - deploy

before_script:  # global before_script is run before each and every job.
  - source venv/bin/activate

################
# STAGE: SETUP #
################

build:
  stage: build
  before_script:
    - python -V
    - pip install --upgrade pip virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install --upgrade wheel
    - python setup.py sdist bdist_wheel
    - pip install --upgrade -r requirements.txt
    - pip install --upgrade -e .
  artifacts:
    paths:
      - dist/*.whl

###################
# STAGE: ANALYSIS #
###################

pylint:
  # see .pylintrc for configuration
  stage: analysis
  needs: [ "build" ]
  script:
    - pip install --upgrade pylint pylint-exit anybadge
    - mkdir pylint
    - pylint $TESTDIR || pylint-exit $?
    - pylint $MODULEDIR | tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/

flake8:
  # see .flake8 for configuration
  stage: analysis
  needs: [ "build" ]
  script:
    - pip install --upgrade flake8
    - flake8 $MODULEDIR
    - flake8 $TESTDIR

mypy:
  # see .mpypy.ini for configuration
  stage: analysis
  needs: [ "build" ]
  script:
    - pip install --upgrade mypy
    - mypy --install-types --non-interactive $MODULEDIR
    - mypy --install-types --non-interactive $TESTDIR

###############
# STAGE: TEST #
###############

pytest:
  # see pytest.ini for configuration
  stage: test
  needs: [ "build" ]
  script:
    - pip install --upgrade pytest pytest-cov
    - pytest --junitxml=report.xml --cov=$MODULEDIR $TESTDIR
    - coverage
  artifacts:
    # https://software.ismll.uni-hildesheim.de/help/ci/unit_test_reports
    when: on_success
    reports:
      cobertura: coverage.xml
      junit: report.xml

#################
# STAGE: DEPLOY #
#################

pypi:
  # https://docs.gitlab.com/ee/user/packages/pypi_repository/
  stage: deploy
  only: [ master ]
  allow_failure: true
  script:
    - pip install --upgrade pip twine
    - twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

pages:
  # https://docs.gitlab.com/ee/user/packages/pypi_repository/
  stage: deploy
  only: [ master ]
  allow_failure: true
  needs: [ "build" ]
  script:
    - pip install --upgrade sphinx sphinx-rtd-theme sphinx-math-dollar
    - cd docs
    - make html
  after_script:  # note: after_script resets working dir
    - mv  docs/_build/html/  public/
  artifacts:
    when: on_success
    paths:
      - public
