default:
  image: python:3.9  # official python docker
  tags: [docker]

stages:
  - setup
  - code analysis
  - documentation
  - unit tests


installtion:
  stage: setup
  script:
  - python setup.py bdist_wheel
  artifacts:
   paths:
   - dist/*.whl

flake8:
  stage: code analysis
  allow_failure: true
  before_script:
    - pip install flake8
  script:
    - >
      flake8
      --max-line-length=100 
      --ignore=E203,E221,E226,E241
      tsdm
    # We ignore the following PEP8 Errors:
    # E203 whitespace before ':'
    # E221 multiple spaces before operator
    # E226 missing whitespace around arithmetic operator
    # E241 multiple spaces after ':'


pylint:
  stage: code analysis
  allow_failure: true
  before_script:
      - pip install pylint pylint-exit anybadge torch scipy
      - mkdir ./pylint
  script:
    - >
      pylint 
      --max-line-length=100
      --generated-members=numpy.*,torch.*
      --disable=C0103,C0144
      --output-format=text
      tsdm
      | tee ./pylint/pylint.log || pylint-exit $?
    # We ignore the following PyLint Errors:
    # C0103 invalid-name
    # C0144 non-ascii-name
  after_script:
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/


pages:
  stage: documentation
  allow_failure: true
  before_script:
    - pip install -U sphinx sphinx-rtd-theme sphinx-math-dollar
    - cd docs
  script:
    - make html
  after_script:
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master


tox:
  stage: unit tests
  allow_failure: true
  before_script:
    - pip install tox
  script:
    tox --recreate