exclude: 'bugs/'
minimum_pre_commit_version: 3.6.0
default_language_version:
  python: '3.13'
  node: '22.14.0'
repos:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.10
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--no-dev", "--no-hashes", "--frozen", "--output-file=requirements.txt"]
      - id: uv-sync
        args: ["--upgrade"]
        stages: [ "pre-commit" ]
  # tach
  - repo: https://github.com/gauge-sh/tach-pre-commit
    rev: v0.28.4 # change this to the latest tag!
    hooks:
      - id: tach
  # nbstripout-fast
  - repo: https://github.com/deshaw/nbstripout-fast.git
    rev: v1.0.4
    hooks:
      - id: nbstripout-fast
        exclude: '^docs/'
  # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        name: ruff-isort
        files: '^src/|^tests/'
        args: [ "--select", "I", "--fix" ]
      - id: ruff-format
        files: '^src/|^tests/'
      - id: ruff
        files: '^src/|^tests/'
  # personal hooks
  - repo: https://github.com/randolf-scholz/assorted-hooks.git
    rev: v0.6.15
    hooks:
      # pygrep hooks
      - id: check-separator-length-88
      - id: numpy-rename-axes-axis
      - id: pyarrow-timestamp-seconds
        exclude: '/backend/'
      - id: python-consider-using-raw-string
      - id: python-system-exit
      - id: python-match-case-builtins
      # ast-based hooks
      - id: check-direct-imports
      - id: check-dunder-all
        files: '^src/'
      - id: check-typing
        args: ["--check-no-return-union", "--check-concrete"]
        files: '^src/|^tests/'
        exclude: "lazydict.py"
      - id: check-no-mixed-args
        files: '^src/'
        args:
          - "--ignore-names"
          - "forward"
          - "predict"
          - "--ignore-decorators"
          - "jit.script"
          - "jit.export"
          - "torch.no_grad"
          - "--allow-two"
          - "--"
      # script-based hooks
      - id: check-clean-interface
        files: '^src/'
        exclude: '/tests/'
      - id: update-requirements
      - id: check-requirements-valid
      - id: check-requirements-maintained
      - id: check-requirements-used
        args: ["--known-unimported", "tensorboard", "pydantic", "--"]
      # other hooks
      - id: check-archived-hooks
      - id: check-resolved-github-issues
        files: '^src/|^tests/'
  # markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args:
          - "--disable" # disable rules
          - "MD013"     # Line length
          - "MD033"     # Inline HTML
          - "--"        # otherwise files are interpreted as args
  # shellcheck
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-x", "--shell=bash", "--color=always", "--format=gcc", "--"]
  - repo: local
    hooks:
      - id: unknown-inline-pragma
        name: unknown-inline-pragma
        description: "Check for unknown inline pragmas."
        language: pygrep
        entry: '^[^\n]*\S[^\n]*\#\x20+(?!type|pyright|noqa|fmt|shape|mypy|ruff|FIXME|SEE|NOTE|TODO)\w+:[^\n]+$'
        types: [python]
        files: '^src/|^tests/'
      - id: double-comment
        name: double-comment
        description: "Check for double comments."
        language: pygrep
        entry: '\#\s+\#\s+'
        types: [python]
        files: '^src/|^tests/'
  # pyright
  - repo: https://github.com/randolf-scholz/assorted-hooks.git
    rev: v0.6.15
    hooks:
      - id: pyright-concise
        files: '^src/|^tests/'
        exclude: '/tasks/'
  # mypy
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        require_serial: true
        types_or: [python, pyi]
        files: '^src/|^tests/'
        exclude: '/tasks/'
        entry: mypy
        args:
          - "--hide-error-context"
          - "--hide-error-end"
          - "--no-pretty"
          - "--"
