exclude: bugs/
minimum_pre_commit_version: 3.6.0
default_language_version:
  python: python3.12
  node: "20.10.0"
repos:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff-format
        files: '^src/|^tests/'
      - id: ruff
        name: ruff-isort
        files: '^src/|^tests/'
        args: ["--select", "I", "--fix"]
      - id: ruff
        files: '^src/|^tests/'
  # uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.11
    hooks:
      - id: uv-lock
      - id: uv-export
  # nbstripout-fast
  - repo: https://github.com/deshaw/nbstripout-fast.git
    rev: v1.0.4
    hooks:
      - id: nbstripout-fast
        exclude: '^experiments/'
  # personal hooks
  - repo: https://github.com/randolf-scholz/assorted-hooks.git
    rev: v0.5.52
    hooks:
      # pygrep hooks
      - id: check-separator-length-88
      - id: pyarrow-timestamp-seconds
      - id: python-consider-using-raw-string
      - id: python-rename-axes-axis
      - id: python-system-exit
      - id: python-match-case-builtins
      # ast-based hooks
      - id: check-direct-imports
      - id: check-dunder-all
        files: '^src/'
      - id: check-typing
        args: ["--check-no-return-union", "--check-concrete"]
        files: '^src/|^tests/'
        exclude: "lazydict.py"
      - id: check-no-mixed-args
        files: '^src/'
        args:
          - "--ignore-names"
          - "forward"
          - "predict"
          - "--ignore-decorators"
          - "jit.script"
          - "jit.export"
          - "torch.no_grad"
          - "--allow-two"
          - "--"
      # script-based hooks
      - id: update-requirements
      - id: check-requirements-valid
      - id: check-requirements-maintained
      - id: check-requirements-used
        args: ["--known-unimported", "tensorboard", "pydantic", "--"]
      - id: check-clean-interface
        files: '^src/'
        exclude: '/tests/'
      # other hooks
      - id: check-archived-hooks
      - id: check-resolved-github-issues
        files: '^src/|^tests/'
  # markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args:
          - "--disable" # disable rules
          - "MD013"     # Line length
          - "MD033"     # Inline HTML
          - "--"        # otherwise files are interpreted as args
  # shellcheck
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-x", "--shell=bash", "--color=always", "--format=gcc", "--"]
  # tach
  - repo: https://github.com/gauge-sh/tach-pre-commit
    rev: v0.19.0 # change this to the latest tag!
    hooks:
      - id: tach
  - repo: local
    hooks:
      - id: unknown-inline-pragma
        name: unknown-inline-pragma
        description: "Check for unknown inline pragmas."
        language: pygrep
        entry: '^([^#]*[^\#\s][^#]*)\#\s+(?!(type|pyright|noqa|fmt|shape|mypy|ruff|FIXME|SEE|NOTE|TODO):)([\w\s]+:)'
        types: [python]
      - id: double-comment
        name: double-comment
        description: "Check for double comments."
        language: pygrep
        entry: '\#\s*\#'
        types: [python]
        files: '^src/|^tests/'
  # pyright
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.391
    hooks:
      - id: pyright
        # SEE: https://stackoverflow.com/a/20401674
        #        entry: sh -c '! script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)"' --
        # simple grep: grep --color=never -Po "$PWD/.*:.*"
        # better ripgrep: rg --multiline --multiline-dotall "($PWD/[^\n]*?)(?:\n.*?)?(\(report\w+\))" -or '$1 $2'
        # perl:  perl -0777 -ne "while (/((?:\x20+)(${path}[^\n\r]*?)(?:[\r\n].*?)?(\(report\w+\)))/gms) { print \"\$1 \$2\n\"}"
        # FIXME: some weird issues with ripgrep + script.
        # NOTE: The issue is likely control characters that are not being handled correctly.
        #   In fact, it turns out the problem is precisely carriage return. We need to check [\n\r] instead of just \n
        entry: |
          bash -c '
              path="${PWD//\//\\/}";
              grey="\x1b\[90m"
              end="\x1b\[0m"
              code_group="(${grey}).*?\(report(\w+)\)";
              git_root=$(git rev-parse --show-toplevel);
              regex="\x20+(?:${git_root})/([^\r\n]*?)(?:[\r\n].*?)?${code_group}";
              output="\$1 \$2(\$3)";
              result=$(script -fqc "pyright $*" /dev/null | rg --multiline --multiline-dotall "$regex" -or "$output");
              count=$(echo -n "$result" | grep -c "^");
              if [ "$count" -ne 0 ]; then
                  echo "$result";
                  echo -e "\033[1;31mFound ${count} error(s)\033[0m";
                  exit 1;
              fi
          ' --
        files: '^src/|^tests/'
        exclude: '/tasks/'
  # mypy
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        require_serial: true
        types_or: [python, pyi]
        files: '^src/|^tests/'
        exclude: '/tasks/'
        entry: mypy
        args:
          - "--hide-error-context"
          - "--hide-error-end"
          - "--no-pretty"
          - "--"
