#[build-system]
#requires = ["setuptools", "wheel"]
#build-backend = "setuptools.build_meta"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tsdm"
version = "0.2.2"
description = "Time-Series Datasets and Models"
authors = ["Randolf Scholz <rscholz@ismll.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
h5py = ">=3.4.0"
matplotlib = ">=3.4"
modin = ">=0.12"
numba = ">=0.55"
numpy = ">=1.21"
pandas = ">=1.3"
pyarrow = ">=6.0"
PyYAML = ">=6.0"
ray = ">=1.6"
scikit-learn = ">=1.0"
scipy = ">=1.7"
tables = ">=3.6"
tensorboard = ">=2.7"
torch = ">=1.10"
tqdm = ">=4.50"
xarray = ">=0.20"

[tool.poetry.dev-dependencies]
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-autoapi = "^1.8.4"
black = "^21.12b0"
isort = "^5.10.1"
pycodestyle = "^2.8.0"
pydocstyle = "^6.1.1"
mypy = "^0.931"
pylint = "^2.12.2"
pylint-gitlab = "^1.0.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-rerunfailures = "^10.2"
types-PyYAML = "^6.0.3"
types-backports = "^0.1.3"
types-protobuf = "^3.19.0"
types-pyOpenSSL = "^21.0.3"
types-redis = "^4.1.8"
types-requests = "^2.27.7"
types-setuptools = "^57.4.7"
types-six = "^1.16.9"
types-tabulate = "^0.8.5"
types-toml = "^0.10.3"
types-futures = "^3.3.2"
types-cryptography = "^3.3.12"
types-enum34 = "^1.1.2"
types-ipaddress = "^1.0.2"
flake8 = "^4.0.1"
flake8-annotations = "^2.7.0"
flake8-black = "^0.2.3"
flake8-bugbear = "^22.1.11"
flake8-comprehensions = "^3.8.0"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
flake8-mutable = "^1.2.0"
flake8-nb = "^0.3.1"
flake8-pyi = "^20.10.0"
flake8-rst = "^0.8.0"
flake8-rst-docstrings = "^0.2.5"
setuptools = "^60.5.0"
twine = "^3.7.1"
wheel = "^0.37.1"

########################
# PyLint Configuration #
########################
[tool.pylint]
[tool.pylint."MESSAGES CONTROL"]
enable= [
    "useless-suppression",
]
disable= [
    "C0103",  # invalid-name
    "C0144",  # non-ascii-name
    "R0801",  # similar lines
    "W0511",  # (fixme) (todos)
    "R0902",  # too-many-instance-attributes
    "R0915",  # too-many-statements
    "R0914",  # too-many-locals
]

[tool.pylint.REPORTS]
# Set the output format. Available formats are text, parseable, colorized, json and
# msvs (visual studio). You can also give a reporter class, e.g. mypackage.mymodule.MyReporterClass
output-format="colorized"

[tool.pylint.FORMAT]
max-line-length=100

[tool.pylint.TYPECHECK]
# List of members which are set dynamically and missed by pylint inference system, and so shouldn't
# trigger E1101 when accessed. Python regular expressions are accepted.
generated-members=["numpy.*","torch.*"]


########################
# PyTest Configuration #
########################
[tool.pytest.ini_options]
testpaths = [ "test" ]
reruns = "3"
only_rerun = "AssertionError"


######################
# MyPy Configuration #
######################
[tool.mypy]
allow_redefinition = true
color_output = true
error_summary = true
files = ["tsdm", "test"]
plugins = "numpy.typing.mypy_plugin"
pretty = true
python_version = "3.9"
show_column_numbers = true
show_error_codes = true
warn_unused_ignores = true
#mypy_path="/home/rscholz/GIT/CONTRIBUTING/pandas-stubs/third_party/3"
[[tool.mypy.overrides]]
module = [
    "h5py.*",
    "matplotlib.*",
    "modin.*",
    "numba.*",
    "pandas.*",
    "sklearn.*",
    "scipy.*",
    "tqdm.*",
]
ignore_missing_imports = true


#######################
# isort Configuration #
#######################
[tool.isort]
# isort profiles: black, django, pycharm, google, open_stack, plone, attrs, hug, wemake, appnexus
# black-compatible: black, appnexus
profile="black"
src_paths=["tsdm", "test"]
py_version=39
# flake8-profiles: appnexus, cryptography, edited, google, pep8, pycharm, smarkets
# black-compatible: black, appnexus

#######################
# black Configuration #
#######################
[tool.black]
line-length = 88
target-version = ['py39']
color = true

############################
# pydocstyle Configuration #
############################
[tool.pydocstyle]
convention = "numpy"
#count = true

#########################
# pyright Configuration #
#########################
[tool.pyright]
pythonVersion = "3.9"
reportMissingImports = false
reportUnsupportedDunderAll = false

