# We will use pyproject.toml once PEP 660 (https://www.python.org/dev/peps/pep-0660) support is added

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

########################
# Poetry Configuration #
########################

#[build-system]
#requires = ["poetry-core>=1.0.0"]
#build-backend = "poetry.core.masonry.api"

#[tool.poetry]
#name = "tsdm"
#version = "0.1.0"
#description = "Time Series Datasets and Models"
#authors = ["Randolf Scholz <rscholz@ismll.de>"]
#license = "MIT"
#
#[tool.poetry.dependencies]
#python = ">=3.9, <3.10"
#numpy = ">=1.21"
#pandas = ">=1.3"
#scipy = ">=1.7"
#h5py = ">=3.1"
#numba = ">=0.53"
#xarray = ">=0.18"
#PyYAML = ">=5.4"
#matplotlib = ">=3.4"
#tables = ">=3.6"
#
#[tool.poetry.dev-dependencies]
#mypy = ">=0.910"
#pylint = ">=2.9"
#flake8 = ">=3.9"
#pytest = ">=6.2"
#pytest-cov = ">=2.12"
#coverage = ">=5.5"
#twine = ">=3.3"
#Sphinx = ">=4.0"
#sphinx-math-dollar = ">=1.2"
#sphinx-rtd-theme = ">=0.5.2"
#wheel = ">=0.36.2"
#virtualenv = ">=20.4"
#pip = ">=21.1.3"

########################
# PyLint Configuration #
########################
[tool.pylint]
[tool.pylint.'MESSAGES CONTROL']
disable= [
    "C0103",  # invalid-name
    "C0144",  # non-ascii-name
    "R0801",  # similar lines
    "W0511",  # (fixme) (todos)
]

[tool.pylint.REPORTS]
# Set the output format. Available formats are text, parseable, colorized, json and
# msvs (visual studio). You can also give a reporter class, e.g. mypackage.mymodule.MyReporterClass
output-format="colorized"

[tool.pylint.FORMAT]
max-line-length=100

[tool.pylint.TYPECHECK]
# List of members which are set dynamically and missed by pylint inference system, and so shouldn't
# trigger E1101 when accessed. Python regular expressions are accepted.
generated-members=["numpy.*","torch.*"]


########################
# PyTest Configuration #
########################
[tool.pytest.ini_options]
testpaths = [ "test" ]
reruns = "3"
only_rerun = "AssertionError"


######################
# MyPy Configuration #
######################
[tool.mypy]
files = ["tsdm", "test"]
python_version = "3.9"
color_output = true
error_summary = true
show_error_codes = true
show_column_numbers = true
plugins = "numpy.typing.mypy_plugin"
pretty = true

[[tool.mypy.overrides]]
module = [
    "h5py.*",
    "matplotlib.*",
    "modin.*",
    "numba.*",
    "pandas.*",
    "sklearn.*",
    "scipy.*",
    "tqdm.*",
]
ignore_missing_imports = true


#######################
# isort Configuration #
#######################
[tool.isort]
# isort profiles: black, django, pycharm, google, open_stack, plone, attrs, hug, wemake, appnexus
# black-compatible: black, appnexus
profile="black"
src_paths=["tsdm", "test"]
py_version=39
# flake8-profiles: appnexus, cryptography, edited, google, pep8, pycharm, smarkets
# black-compatible: black, appnexus

#######################
# black Configuration #
#######################
[tool.black]
line-length = 88
target-version = ['py39']
color = true

############################
# pydocstyle Configuration #
############################
[tool.pydocstyle]
convention = "numpy"
#count = true
