# This is currently cluttered, but will be cleaned up in the future
name: kiwif
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
    - python
    - blas=*=mkl
# pytorch
    - pytorch>=1.8.1
    - torchvision
    - torchaudio
# scipy stack
    - numpy
    - scipy
    - matplotlib
    - ipython
    - pandas
    - sympy
    - nose
# jupyter
    - jupyter
    - jupyterlab
    - nodejs
    - ipympl
    - parso
    - ipywidgets
    - jupyter_server
    - anyio
# arrays
    - dask
    - xarray
    - pytables
# graph analysis
    - networkx
# machine learning
    - scikit-learn
    - statsmodels
    - gym
    - openml
# linting
    - pylint
    - pycodestyle
    - flake8
# documentation
    - sphinx
    - sphinx-math-dollar
    # - sphinx-autodoc-typehints
    - myst-parser
    - numpydoc
# data
    - h5py
    - imageio
# other
    - vispy     # plotting
    - plotly
    - pyopengl
    - sortedcontainers
    - tqdm
    - kaggle
    - numba
# utility
    - git
    - perl
    - curl