interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = ["src"]

[[modules]]
path = "tsdm"
depends_on = [
    "tsdm.backend",
    "tsdm.datasets",
    "tsdm.datatools",
    "tsdm.encoders",
    "tsdm.linalg",
    "tsdm.logutils",
    "tsdm.losses",
    "tsdm.pretrained",
    "tsdm.random",
    "tsdm.tasks",
    "tsdm.timeseries",
    "tsdm.types",
    "tsdm.viz",
]

[[modules]]
path = "tsdm.backend"
depends_on = ["tsdm.types"]

[[modules]]
path = "tsdm.config"
depends_on = []
utility = true

[[modules]]
path = "tsdm.constants"
depends_on = []
utility = true

[[modules]]
path = "tsdm.datasets"
depends_on = [
    "tsdm.datatools",
    "tsdm.random",
    "tsdm.testing",
    "tsdm.types",
]

[[modules]]
path = "tsdm.datatools"
depends_on = [
    "tsdm.backend",
    "tsdm.types",
]

[[modules]]
path = "tsdm.decorator"
depends_on = ["tsdm.types"]

[[modules]]
path = "tsdm.encoders"
depends_on = [
    "tsdm.encoders.universal",
    "tsdm.testing",
    "tsdm.types",
]

[[modules]]
path = "tsdm.encoders.universal"
depends_on = [
    "tsdm.backend",
    "tsdm.datatools",
    "tsdm.encoders",
    "tsdm.linalg",
    "tsdm.types",
]

[[modules]]
path = "tsdm.linalg"
depends_on = ["tsdm.types"]

[[modules]]
path = "tsdm.logutils"
depends_on = [
    "tsdm.datatools",
    "tsdm.linalg",
    "tsdm.losses",
    "tsdm.types",
    "tsdm.viz",
]

[[modules]]
path = "tsdm.losses"
depends_on = []

[[modules]]
path = "tsdm.pretrained"
depends_on = [
    "tsdm.testing",
    "tsdm.encoders",
    "tsdm.types",
]

[[modules]]
path = "tsdm.pprint"
depends_on = [
    "tsdm.types",
    "tsdm.testing",
    "tsdm.decorator",
    "tsdm.datatools",
]
utility = true

[[modules]]
path = "tsdm.random"
depends_on = [
    "tsdm.datatools",
    "tsdm.types",
]

[[modules]]
path = "tsdm.testing"
depends_on = ["tsdm.types", "tsdm.datatools"]

[[modules]]
path = "tsdm.tasks"
depends_on = [
    "tsdm.datasets",
    "tsdm.datatools",
    "tsdm.encoders",
    "tsdm.losses",
    "tsdm.random",
    "tsdm.timeseries",
    "tsdm.types",
]

[[modules]]
path = "tsdm.timeseries"
depends_on = [
    "tsdm.datasets",
    "tsdm.datatools",
]

[[modules]]
path = "tsdm.types"
depends_on = []

[[modules]]
path = "tsdm.utils"
depends_on = [
    "tsdm.types",
    "tsdm.testing",
]
utility = true

[[modules]]
path = "tsdm.viz"
depends_on = []
