#!/usr/bin/env just --justfile

[default]
[doc('List available commands.')]
help:
    @just --justfile {{ justfile() }} --list --unsorted

[doc('Profile tsdm import time with tuna.')]
time-imports:
    #!/usr/bin/env bash
    dependencies=(
      torch
      torch.utils.tensorboard
      pandas
      pyarrow
      pyarrow.compute
      pyarrow.parquet
      polars
      numpy
      scipy.stats
      sklearn.model_selection
      matplotlib.pyplot
    )
    # get project root with git
    cd "$(git rev-parse --show-toplevel)" || exit
    echo "Project root: $(pwd)"
    IFS=,
    uv run python -X importtime -c \
      "import ${dependencies[*]}; import tsdm" \
      2> tests/import_time.log
    uv run tuna tests/import_time.log
