# default configuration for tsdm

# folder structure
basedir: ".tsdm"
logdir: "logs"
modeldir: "models"
datasetdir: "datasets"
rawdatadir: "rawdata"

folders:
  datasets:
  models:
  logs:
  rawdata:
