r"""Protocols for linear algebra types."""

__all__ = [
    # Comparison Protocols
    "SupportsArrayEquality",
    "SupportsArrayComparison",
    # Generic Protocols
    "BaseArray",
    "ArraySupportsComparison",
    "ArrayType",
    "TimeLikeArray",
    "SpanLikeArray",
    # Python scalar compatible Array Protocols
    "BooleanArray",
    "IntegerArray",
    "FloatArray",
    "ComplexArray",
    "TimedeltaArray",
    "DatetimeArray",
]

from datetime import datetime, timedelta
from typing import (
    Any,
    Protocol,
    Self,
    overload,
    runtime_checkable,
)

from numpy.typing import NDArray

from tsdm.types.numerical.mixins import SupportsArray, SupportsDtype, SupportsShape
from tsdm.types.numerical.scalars import (
    BoolScalar,
    ComplexScalar,
    FloatScalar,
    IntScalar,
    OrderedScalar,
    SpanLikeScalar,
    TimeLikeScalar,
)


@runtime_checkable
class ArrayType[V](Protocol):
    r"""An n-dimensional container type convertible to a numpy array.

    Examples:
        - `numpy.ndarray`
        - `pandas.DataFrame`
        - `pandas.Series`
        - `pandas.extensions.ExtensionArray`
        - `polars.DataFrame`
        - `polars.Series`
        - `pyarrow.Array`
        - `pyarrow.Table`
        - `torch.Tensor`

    References:
        - https://docs.python.org/3/c-api/buffer.html
        - https://numpy.org/doc/stable/reference/arrays.interface.html
        - https://numpy.org/devdocs/user/basics.interoperability.html
    """

    @property
    def shape(self) -> tuple[int, ...]: ...
    def __array__(self) -> NDArray: ...
    def __len__(self) -> int: ...


class SupportsArrayEquality(Protocol):
    r"""Protocol for array-like types supporting equality comparisons."""

    # equality ==
    def __eq__(self, other: Any, /) -> BooleanArray: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    # inequality !=
    def __ne__(self, other: Any, /) -> BooleanArray: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]


class SupportsArrayComparison[ScalarT](Protocol):  # noqa: D101
    # comparisons (element-wise)
    def __le__(self, other: Self | ScalarT, /) -> BooleanArray: ...
    def __ge__(self, other: Self | ScalarT, /) -> BooleanArray: ...
    def __lt__(self, other: Self | ScalarT, /) -> BooleanArray: ...
    def __gt__(self, other: Self | ScalarT, /) -> BooleanArray: ...


class BaseArray(
    SupportsArray,
    SupportsDtype,
    SupportsShape,
    Protocol,
):
    r"""Common Protocol for array-like types."""

    def __array__(self) -> NDArray: ...  # removal candidate

    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> Any: ...

    def __len__(self) -> int: ...
    def __contains__(self, element: Any, /) -> bool: ...
    def __getitem__(self, key: Any, /) -> Self: ...

    # equality ==
    def __eq__(self, other: Any, /) -> BooleanArray: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    # inequality !=
    def __ne__(self, other: Any, /) -> BooleanArray: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]


class ArraySupportsComparison[ScalarT: OrderedScalar](  # noqa: D101
    BaseArray,
    SupportsArrayComparison[ScalarT],
    Protocol,
):
    # comparisons (element-wise)
    def __le__(self, other: Self | ScalarT, /) -> BooleanArray: ...
    def __ge__(self, other: Self | ScalarT, /) -> BooleanArray: ...
    def __lt__(self, other: Self | ScalarT, /) -> BooleanArray: ...
    def __gt__(self, other: Self | ScalarT, /) -> BooleanArray: ...


@runtime_checkable
class BooleanArray[T](
    BaseArray,
    Protocol,
):
    r"""Protocol for boolean array-like types supporting standard boolean operations."""

    # Using Protocol here to allow for different return types
    def __invert__(self) -> Self: ...
    def all(self) -> Self | BoolScalar | Any: ...
    def any(self) -> Self | BoolScalar | Any: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    def __and__(self, other: Self | T | bool, /) -> Self: ...
    def __rand__(self, other: Self | T | bool, /) -> Self: ...

    def __or__(self, other: Self | T | bool, /) -> Self: ...
    def __ror__(self, other: Self | T | bool, /) -> Self: ...

    def __xor__(self, other: Self | T | bool, /) -> Self: ...
    def __rxor__(self, other: Self | T | bool, /) -> Self: ...

    # endregion binary  operations -----------------------------------------------------

    # region comparison operations -----------------------------------------------------
    def __eq__(self, other: Self | T | Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __ne__(self, other: Self | T | Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __lt__(self, other: Self | T | Any, /) -> Self: ...
    def __le__(self, other: Self | T | Any, /) -> Self: ...
    def __gt__(self, other: Self | T | Any, /) -> Self: ...
    def __ge__(self, other: Self | T | Any, /) -> Self: ...

    # endregion comparison operations --------------------------------------------------


@runtime_checkable
class IntegerArray[T](
    ArraySupportsComparison[float],
    Protocol,
):
    r"""Protocol for integer array-like types supporting standard arithmetic operations."""

    def clip(self, lower: Any, upper: Any, /) -> Self: ...

    # aggregations
    def min(self) -> Self | IntScalar | Any: ...
    def max(self) -> Self | IntScalar | Any: ...
    def sum(self) -> Self | IntScalar | Any: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # ~ (bitwise NOT)
    def __invert__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # + (addition)
    def __add__(self, other: Self | T | int, /) -> Self: ...
    def __radd__(self, other: Self | T | int, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | T | int, /) -> Self: ...
    def __rsub__(self, other: Self | T | int, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | T | int, /) -> Self: ...
    def __rmul__(self, other: Self | T | int, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | T | int, /) -> Self: ...
    def __rpow__(self, base: Self | T | int, /) -> Self: ...
    # // (floor division)
    def __floordiv__(self, other: Self | T | int, /) -> Self: ...
    def __rfloordiv__(self, other: Self | T | int, /) -> Self: ...
    # % (modulo)
    def __mod__(self, other: Self | T | int, /) -> Self: ...
    def __rmod__(self, other: Self | T | int, /) -> Self: ...
    # & (bitwise AND)
    def __and__(self, other: Self | T | int, /) -> Self: ...
    def __rand__(self, other: Self | T | int, /) -> Self: ...
    # | (bitwise OR)
    def __or__(self, other: Self | T | int, /) -> Self: ...
    def __ror__(self, other: Self | T | int, /) -> Self: ...
    # ^ (bitwise XOR)
    def __xor__(self, other: Self | T | int, /) -> Self: ...
    def __rxor__(self, other: Self | T | int, /) -> Self: ...

    # @overload
    # def __add__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __add__(self, other: float, /) -> "FloatArray": ...
    # @overload
    # def __radd__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __radd__(self, other: float, /) -> "FloatArray": ...
    # @overload
    # def __mod__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __mod__(self, other: float, /) -> "FloatArray": ...
    # @overload
    # def __rmod__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __rmod__(self, other: float, /) -> "FloatArray": ...
    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class FloatArray[T](
    ArraySupportsComparison[float],
    Protocol,
):
    r"""Protocol for floating-point array-like types supporting standard arithmetic operations."""

    @overload
    def round(self) -> Self: ...
    @overload
    def round(self, *, decimals: int) -> Self: ...
    def clip(self, lower: Any, upper: Any, /) -> Self: ...

    # aggregations
    def min(self) -> Self | FloatScalar | Any: ...
    def max(self) -> Self | FloatScalar | Any: ...
    def mean(self) -> Self | FloatScalar | Any: ...
    def sum(self) -> Self | FloatScalar | Any: ...
    def std(self) -> Self | FloatScalar | Any: ...
    def var(self) -> Self | FloatScalar | Any: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # + (addition)
    def __add__(self, other: Self | T | float, /) -> Self: ...
    def __radd__(self, other: Self | T | float, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | T | float, /) -> Self: ...
    def __rsub__(self, other: Self | T | float, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | T | float, /) -> Self: ...
    def __rmul__(self, other: Self | T | float, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | T | float, /) -> Self: ...
    def __rpow__(self, base: Self | T | float, /) -> Self: ...
    # / (true division)
    def __truediv__(self, other: Self | T | float, /) -> Self: ...
    def __rtruediv__(self, other: Self | T | float, /) -> Self: ...
    # // (floor division)
    def __floordiv__(self, other: Self | T | float, /) -> Self: ...
    def __rfloordiv__(self, other: Self | T | float, /) -> Self: ...
    # % (modulo)
    def __mod__(self, other: Self | T | float, /) -> Self: ...
    def __rmod__(self, other: Self | T | float, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class ComplexArray[T](
    BaseArray,
    Protocol,
):
    r"""Protocol for complex array-like types supporting standard arithmetic operations."""

    # aggregations
    def sum(self) -> Self | ComplexScalar | Any: ...
    def mean(self) -> Self | ComplexScalar | Any: ...
    def std(self) -> FloatArray | FloatScalar: ...
    def var(self) -> FloatArray | FloatScalar: ...

    # absolute value abs()
    def __abs__(self) -> FloatArray: ...
    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # + (addition)
    def __add__(self, other: Self | T | complex, /) -> Self: ...
    def __radd__(self, other: Self | T | complex, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | T | complex, /) -> Self: ...
    def __rsub__(self, other: Self | T | complex, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | T | complex, /) -> Self: ...
    def __rmul__(self, other: Self | T | complex, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | T | complex, /) -> Self: ...
    def __rpow__(self, base: Self | T | complex, /) -> Self: ...
    # / (true division)
    def __truediv__(self, other: Self | T | complex, /) -> Self: ...
    def __rtruediv__(self, other: Self | T | complex, /) -> Self: ...

    # // (floor division) -- not supported for complex numbers, so omitted
    # % (modulo) -- not supported for complex numbers, so omitted
    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class SpanLikeArray[
    SpanT: SpanLikeScalar = Any,
](
    ArraySupportsComparison[SpanT],
    Protocol,
):
    r"""Protocol for timedelta array-like types supporting standard timedelta operations."""

    def min(self) -> Self | SpanLikeScalar | Any: ...
    def max(self) -> Self | SpanLikeScalar | Any: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # + (addition)
    def __add__(self, other: Self | SpanT, /) -> Self: ...
    def __radd__(self, other: Self | SpanT, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | SpanT, /) -> Self: ...
    def __rsub__(self, other: Self | SpanT, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...
    # / (division)
    # @overload  # NOTE: 'Self | Any' to fix numpy overload issue
    # def __truediv__(self, other: int, /) -> Self | Any: ...
    # @overload
    def __truediv__(self, other: Self | SpanT, /) -> FloatArray: ...

    # FIXME: disabled since not supported by all implementations
    # # // (floor division)
    # @overload
    # def __floordiv__(self, other: int, /) -> Self: ...
    # @overload
    # def __floordiv__(self, other: Self | T, /) -> IntegerArray: ...
    # # % (modulo)
    # def __mod__(self, other: Self, /) -> Self: ...
    # # divmod
    # def __divmod__(self, other: Self | T, /) -> tuple[IntegerArray, Self]: ...


@runtime_checkable
class TimedeltaArray[SpanT: SpanLikeScalar = Any](
    SpanLikeArray[SpanT | timedelta],
    Protocol,
):
    r"""Protocol for timedelta array-like types supporting standard timedelta operations."""


@runtime_checkable
class TimeLikeArray[
    TimeT: TimeLikeScalar = Any,
    DualT: SpanLikeScalar = Any,
](
    ArraySupportsComparison[TimeT],
    Protocol,
):
    r"""Protocol for timestamp array-like types supporting standard datetime operations."""

    def min(self) -> Self | TimeLikeScalar | Any: ...
    def max(self) -> Self | TimeLikeScalar | Any: ...

    # + (addition with timedelta)
    def __add__(self, other: DualT, /) -> Self: ...
    def __radd__(self, other: DualT, /) -> Self: ...
    # - (subtraction with datetime)
    def __sub__(self, other: Self | TimeT, /) -> DualT: ...
    def __rsub__(self, other: Self | TimeT, /) -> DualT: ...


@runtime_checkable
class DatetimeArray[
    TimeT: TimeLikeScalar = Any,
    DualT: SpanLikeScalar = Any,
](
    TimeLikeArray[TimeT | datetime, DualT | timedelta],
    Protocol,
):
    r"""Protocol for datetime array-like types supporting standard datetime operations."""
