[icu]
[icu.chartevents]
subject_id = "uint32"
hadm_id = "uint32"
stay_id = "uint32"
caregiver_id = "uint32"
itemid = "uint32"
charttime = "timestamp[s]"
storetime = "timestamp[s]"
value = "string"
valuenum = "float32"
valueuom = "dictionary[int32,string]"
warning = "bool"

[icu.inputevents]
subject_id = "uint32"
hadm_id = "uint32"
stay_id = "uint32"
caregiver_id = "uint32"
starttime = "timestamp[s]"
endtime = "timestamp[s]"
storetime = "timestamp[s]"
itemid = "uint32"
amount = "float32"
amountuom = "dictionary[int32,string]"
rate = "float32"
rateuom = "dictionary[int32,string]"
orderid = "uint32"
linkorderid = "uint32"
ordercategoryname = "dictionary[int32,string]"
secondaryordercategoryname = "dictionary[int32,string]"
ordercomponenttypedescription = "dictionary[int32,string]"
ordercategorydescription = "dictionary[int32,string]"
patientweight = "float32"
totalamount = "float32"
totalamountuom = "dictionary[int32,string]"
isopenbag = "bool"
continueinnextdept = "bool"
statusdescription = "dictionary[int32,string]"
originalamount = "float32"
originalrate = "float32"

[icu.outputevents]
subject_id = "uint32"
hadm_id = "uint32"
stay_id = "uint32"
caregiver_id = "uint32"
charttime = "timestamp[s]"
storetime = "timestamp[s]"
itemid = "uint32"
value = "float32"
valueuom = "dictionary[int32,string]"

[icu.procedureevents]
subject_id = "uint32"
hadm_id = "uint32"
stay_id = "uint32"
caregiver_id = "uint32"
starttime = "timestamp[s]"
endtime = "timestamp[s]"
itemid = "uint32"
value = "float32"
valueuom = "dictionary[int32,string]"
location = "dictionary[int32,string]"
locationcategory = "dictionary[int32,string]"
orderid = "uint32"
linkorderid = "uint32"
ordercategoryname = "dictionary[int32,string]"
ordercategorydescription = "dictionary[int32,string]"
patientweight = "float32"
isopenbag = "bool"
continueinnextdept = "bool"
statusdescription = "dictionary[int32,string]"
originalamount = "float32"
originalrate = "bool"

[icu.datetimeevents]
subject_id = "uint32"
hadm_id = "uint32"
stay_id = "uint32"
caregiver_id = "uint32"
charttime = "timestamp[s]"
storetime = "timestamp[s]"
itemid = "uint32"
value = "timestamp[s]"
valueuom = "dictionary[int32,string]"
warning = "bool"

[icu.ingredientevents]
subject_id = "uint32"
hadm_id = "uint32"
stay_id = "uint32"
caregiver_id = "uint32"
starttime = "timestamp[s]"
endtime = "timestamp[s]"
storetime = "timestamp[s]"
itemid = "uint32"
amount = "float32"
amountuom = "dictionary[int32,string]"
rate = "float32"
rateuom = "dictionary[int32,string]"
orderid = "uint32"
linkorderid = "uint32"
statusdescription = "dictionary[int32,string]"
originalamount = "float32"
originalrate = "float32"

[icu.icustays]
subject_id = "uint32"
hadm_id = "uint32"
stay_id = "uint32"
first_careunit = "dictionary[int32,string]"
last_careunit = "dictionary[int32,string]"
intime = "timestamp[s]"
outtime = "timestamp[s]"
los = "float32"

[icu.d_items]
itemid = "uint32"
label = "string"
abbreviation = "string"
linksto = "dictionary[int32,string]"
category = "dictionary[int32,string]"
unitname = "dictionary[int32,string]"
param_type = "dictionary[int32,string]"
lownormalvalue = "float32"
highnormalvalue = "float32"

[icu.caregiver]
caregiver_id = "uint32"

[hosp]
[hosp.transfers]
subject_id = "uint32"
hadm_id = "uint32"
transfer_id = "uint32"
eventtype = "dictionary[int32,string]"
careunit = "dictionary[int32,string]"
intime = "timestamp[s]"
outtime = "timestamp[s]"

[hosp.admissions]
subject_id = "uint32"
hadm_id = "uint32"
admittime = "timestamp[s]"
dischtime = "timestamp[s]"
deathtime = "timestamp[s]"
admission_type = "dictionary[int32,string]"
admit_provider_id = "dictionary[int32,string]"
admission_location = "dictionary[int32,string]"
discharge_location = "dictionary[int32,string]"
insurance = "dictionary[int32,string]"
language = "dictionary[int32,string]"
marital_status = "dictionary[int32,string]"
race = "dictionary[int32,string]"
edregtime = "timestamp[s]"
edouttime = "timestamp[s]"
hospital_expire_flag = "bool"

[hosp.services]
subject_id = "uint32"
hadm_id = "uint32"
transfertime = "timestamp[s]"
prev_service = "dictionary[int32,string]"
curr_service = "dictionary[int32,string]"

[hosp.provider]
provider_id = "string"

[hosp.procedures_icd]
subject_id = "uint32"
hadm_id = "uint32"
seq_num = "uint32"
chartdate = "date32[day]"
icd_code = "dictionary[int32,string]"
icd_version = "uint32"

[hosp.prescriptions]
subject_id = "uint32"
hadm_id = "uint32"
pharmacy_id = "uint32"
poe_id = "string"
poe_seq = "uint32"
order_provider_id = "dictionary[int32,string]"
starttime = "timestamp[s]"
stoptime = "timestamp[s]"
drug_type = "dictionary[int32,string]"
drug = "dictionary[int32,string]"
formulary_drug_cd = "dictionary[int32,string]"
gsn = "dictionary[int32,string]"
ndc = "dictionary[int32,string]"
prod_strength = "dictionary[int32,string]"
form_rx = "dictionary[int32,string]"
dose_val_rx = "string"
dose_unit_rx = "dictionary[int32,string]"
form_val_disp = "string"
form_unit_disp = "dictionary[int32,string]"
doses_per_24_hrs = "float32"
route = "dictionary[int32,string]"

[hosp.poe_detail]
poe_id = "string"
poe_seq = "uint32"
subject_id = "uint32"
field_name = "dictionary[int32,string]"
field_value = "string"

[hosp.poe]
poe_id = "string"
poe_seq = "uint32"
subject_id = "uint32"
hadm_id = "uint32"
ordertime = "timestamp[s]"
order_type = "dictionary[int32,string]"
order_subtype = "dictionary[int32,string]"
transaction_type = "dictionary[int32,string]"
discontinue_of_poe_id = "string"
discontinued_by_poe_id = "string"
order_provider_id = "dictionary[int32,string]"
order_status = "dictionary[int32,string]"

[hosp.pharmacy]
subject_id = "uint32"
hadm_id = "uint32"
pharmacy_id = "uint32"
poe_id = "string"
starttime = "timestamp[s]"
stoptime = "timestamp[s]"
medication = "dictionary[int32,string]"
proc_type = "dictionary[int32,string]"
status = "dictionary[int32,string]"
entertime = "timestamp[s]"
verifiedtime = "timestamp[s]"
route = "dictionary[int32,string]"
frequency = "dictionary[int32,string]"
disp_sched = "dictionary[int32,string]"
infusion_type = "dictionary[int32,string]"
sliding_scale = "bool"
lockout_interval = "dictionary[int32,string]"
basal_rate = "float32"
one_hr_max = "dictionary[int32,string]"
doses_per_24_hrs = "float32"
duration = "float32"
duration_interval = "dictionary[int32,string]"
expiration_value = "float32"
expiration_unit = "dictionary[int32,string]"
expirationdate = "timestamp[s]"
dispensation = "dictionary[int32,string]"
fill_quantity = "dictionary[int32,string]"

[hosp.patients]
subject_id = "uint32"
gender = "dictionary[int32,string]"
anchor_age = "uint32"
anchor_year = "uint32"
anchor_year_group = "dictionary[int32,string]"
dod = "date32[day]"

[hosp.omr]
subject_id = "uint32"
chartdate = "date32[day]"
seq_num = "uint32"
result_name = "string"
result_value = "string"

[hosp.microbiologyevents]
microevent_id = "uint32"
subject_id = "uint32"
hadm_id = "uint32"
micro_specimen_id = "uint32"
order_provider_id = "dictionary[int32,string]"
chartdate = "timestamp[s]"
charttime = "timestamp[s]"
spec_itemid = "uint32"
spec_type_desc = "dictionary[int32,string]"
test_seq = "uint32"
storedate = "timestamp[s]"
storetime = "timestamp[s]"
test_itemid = "uint32"
test_name = "dictionary[int32,string]"
org_itemid = "uint32"
org_name = "dictionary[int32,string]"
isolate_num = "uint32"
quantity = "dictionary[int32,string]"
ab_itemid = "uint32"
ab_name = "dictionary[int32,string]"
dilution_text = "string"
dilution_comparison = "dictionary[int32,string]"
dilution_value = "float32"
interpretation = "dictionary[int32,string]"
comments = "string"

[hosp.labevents]
labevent_id = "uint32"
subject_id = "uint32"
hadm_id = "uint32"
specimen_id = "uint32"
itemid = "uint32"
order_provider_id = "dictionary[int32,string]"
charttime = "timestamp[s]"
storetime = "timestamp[s]"
value = "string"
valuenum = "float32"
valueuom = "dictionary[int32,string]"
ref_range_lower = "float32"
ref_range_upper = "float32"
flag = "dictionary[int32,string]"
priority = "dictionary[int32,string]"
comments = "string"

[hosp.hcpcsevents]
subject_id = "uint32"
hadm_id = "uint32"
chartdate = "date32[day]"
hcpcs_cd = "dictionary[int32,string]"
seq_num = "uint32"
short_description = "dictionary[int32,string]"

[hosp.emar_detail]
subject_id = "uint32"
emar_id = "string"
emar_seq = "uint32"
parent_field_ordinal = "dictionary[int32,string]"
administration_type = "dictionary[int32,string]"
pharmacy_id = "uint32"
barcode_type = "dictionary[int32,string]"
reason_for_no_barcode = "dictionary[int32,string]"
complete_dose_not_given = "bool"
dose_due = "string"
dose_due_unit = "dictionary[int32,string]"
dose_given = "string"
dose_given_unit = "dictionary[int32,string]"
will_remainder_of_dose_be_given = "bool"
product_amount_given = "string"
product_unit = "dictionary[int32,string]"
product_code = "dictionary[int32,string]"
product_description = "dictionary[int32,string]"
product_description_other = "dictionary[int32,string]"
prior_infusion_rate = "string"
infusion_rate = "string"
infusion_rate_adjustment = "dictionary[int32,string]"
infusion_rate_adjustment_amount = "string"
infusion_rate_unit = "dictionary[int32,string]"
route = "dictionary[int32,string]"
infusion_complete = "bool"
completion_interval = "dictionary[int32,string]"
new_iv_bag_hung = "bool"
continued_infusion_in_other_location = "bool"
restart_interval = "dictionary[int32,string]"
side = "dictionary[int32,string]"
site = "dictionary[int32,string]"
non_formulary_visual_verification = "bool"

[hosp.emar]
subject_id = "uint32"
hadm_id = "uint32"
emar_id = "string"
emar_seq = "uint32"
poe_id = "string"
pharmacy_id = "uint32"
enter_provider_id = "dictionary[int32,string]"
charttime = "timestamp[s]"
medication = "dictionary[int32,string]"
event_txt = "dictionary[int32,string]"
scheduletime = "timestamp[s]"
storetime = "timestamp[s]"

[hosp.drgcodes]
subject_id = "uint32"
hadm_id = "uint32"
drg_type = "dictionary[int32,string]"
drg_code = "uint32"
description = "dictionary[int32,string]"
drg_severity = "uint32"
drg_mortality = "uint32"

[hosp.diagnoses_icd]
subject_id = "uint32"
hadm_id = "uint32"
seq_num = "uint32"
icd_code = "dictionary[int32,string]"
icd_version = "uint32"

[hosp.d_labitems]
itemid = "uint32"
label = "string"
fluid = "dictionary[int32,string]"
category = "dictionary[int32,string]"

[hosp.d_icd_procedures]
icd_code = "string"
icd_version = "uint32"
long_title = "string"

[hosp.d_icd_diagnoses]
icd_code = "string"
icd_version = "uint32"
long_title = "string"

[hosp.d_hcpcs]
code = "string"
category = "uint32"
long_description = "string"
short_description = "dictionary[int32,string]"
