r"""Protocols for linear algebra types."""

__all__ = [
    "SupportsVectorArithmetic",
    "SupportsMutation",
    "SupportsMatmul",
    "SupportsVectorComparison",
    "NumericalArray",
    "NumericalSeries",
    "NumericalTensor",
    "MutableTensor",
    # Dtype-Specific Protocols
    "BaseArray",
    "BooleanArray",
    "IntegerArray",
    "FloatArray",
    "ComplexArray",
    "DatetimeArray",
    "TimedeltaArray",
]


from collections.abc import Iterator
from datetime import datetime, timedelta
from typing import (
    Any,
    Protocol,
    Self,
    SupportsInt,
    overload,
    runtime_checkable,
)

from numpy.typing import NDArray

from tsdm.types.aliases import Axis, MultiIndexer
from tsdm.types.scalars import (
    BoolScalar,
    DurationScalar,
    FloatScalar,
    TimestampScalar,
)


@runtime_checkable
class SupportsVectorArithmetic[Scalar](Protocol):
    r"""Mixin Protocol for arithmetic operations.

    Note:
        Excludes matrix multiplication as well as shift operations.
    """

    # unary operations
    # absolute value abs()
    def __abs__(self) -> Self: ...
    # bitwise NOT ~
    def __invert__(self) -> Self: ...
    # negation -
    def __neg__(self) -> Self: ...
    # positive +
    def __pos__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # arithmetic
    # addition +
    def __add__(self, other: Self | Scalar, /) -> Self: ...
    def __radd__(self, other: Self | Scalar, /) -> Self: ...
    # subtraction -
    def __sub__(self, other: Self | Scalar, /) -> Self: ...
    def __rsub__(self, other: Self | Scalar, /) -> Self: ...
    # multiplication *
    def __mul__(self, other: Self | Scalar, /) -> Self: ...
    def __rmul__(self, other: Self | Scalar, /) -> Self: ...
    # true division /
    def __truediv__(self, other: Self | Scalar, /) -> Self: ...
    def __rtruediv__(self, other: Self | Scalar, /) -> Self: ...
    # floor division //
    def __floordiv__(self, other: Self | Scalar, /) -> Self: ...
    def __rfloordiv__(self, other: Self | Scalar, /) -> Self: ...
    # power **
    def __pow__(self, exponent: Self | Scalar, /) -> Self: ...
    def __rpow__(self, base: Self | Scalar, /) -> Self: ...
    # modulo %
    def __mod__(self, other: Self | Scalar, /) -> Self: ...
    def __rmod__(self, other: Self | Scalar, /) -> Self: ...
    # boolean operations
    # AND &
    def __and__(self, other: Self | Scalar, /) -> Self: ...
    def __rand__(self, other: Self | Scalar, /) -> Self: ...
    # OR |
    def __or__(self, other: Self | Scalar, /) -> Self: ...
    def __ror__(self, other: Self | Scalar, /) -> Self: ...
    # XOR ^
    def __xor__(self, other: Self | Scalar, /) -> Self: ...
    def __rxor__(self, other: Self | Scalar, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class SupportsMutation[Scalar](Protocol):
    """Mixin Protocol for inplace arithmetic operations.

    Note:
        Excludes inplace matrix multiplication as well as inplace shift operations.
    """

    # inplace arithmetic operations
    # addition +=
    def __iadd__(self, other: Self | Scalar, /) -> Self: ...
    # floor division //=
    def __ifloordiv__(self, other: Self | Scalar, /) -> Self: ...
    # modulo %=
    def __imod__(self, other: Self | Scalar, /) -> Self: ...
    # multiplication *=
    def __imul__(self, other: Self | Scalar, /) -> Self: ...
    # power **=
    def __ipow__(self, power: Self | float, /) -> Self: ...
    # subtraction -=
    def __isub__(self, other: Self | Scalar, /) -> Self: ...
    # true division /=
    def __itruediv__(self, other: Self | Scalar, /) -> Self: ...
    # inplace boolean operations
    # AND &=
    def __iand__(self, other: Self | Scalar, /) -> Self: ...
    # OR |=
    def __ior__(self, other: Self | Scalar, /) -> Self: ...
    # XOR ^=
    def __ixor__(self, other: Self | Scalar, /) -> Self: ...


@runtime_checkable
class SupportsVectorComparison[Scalar](Protocol):
    r"""Mixin Protocol for comparison operations."""

    # comparisons (element-wise)
    def __le__(self, other: Self | Scalar, /) -> "BooleanArray": ...
    def __ge__(self, other: Self | Scalar, /) -> "BooleanArray": ...
    def __lt__(self, other: Self | Scalar, /) -> "BooleanArray": ...
    def __gt__(self, other: Self | Scalar, /) -> "BooleanArray": ...

    # region overload alternatives -----------------------------------------------------
    # >>> less than or equal <=
    # >>> @overload
    # >>> def __le__(self, other: Self, /) -> "BooleanArray": ...
    # >>> @overload
    # >>> def __le__(self, other: Scalar, /) -> "BooleanArray": ...
    # >>> # greater than or equal >=
    # >>> @overload
    # >>> def __ge__(self, other: Self, /) -> "BooleanArray": ...
    # >>> @overload
    # >>> def __ge__(self, other: Scalar, /) -> "BooleanArray": ...
    # >>> # less than <
    # >>> @overload
    # >>> def __lt__(self, other: Self, /) -> "BooleanArray": ...
    # >>> @overload
    # >>> def __lt__(self, other: Scalar, /) -> "BooleanArray": ...
    # >>> # greater than >
    # >>> @overload
    # >>> def __gt__(self, other: Self, /) -> "BooleanArray": ...
    # >>> @overload
    # >>> def __gt__(self, other: Scalar, /) -> "BooleanArray": ...
    # endregion overload alternatives --------------------------------------------------


@runtime_checkable
class SupportsMatmul(Protocol):
    r"""Mixin Protocol for matrix multiplication operations."""

    # matrix multiplication @
    def __matmul__(self, other: Self, /) -> Self: ...
    def __rmatmul__(self, other: Self, /) -> Self: ...


class BaseArray(Protocol):
    r"""Common Protocol for array-like types."""

    @property
    def shape(self) -> tuple[int, ...]: ...
    def __array__(self) -> NDArray: ...
    def __len__(self) -> int: ...
    def __contains__(self, element: Any, /) -> bool: ...
    def __getitem__(self, key: Any, /) -> Self: ...

    # equality ==
    def __eq__(self, other: Any, /) -> "BooleanArray": ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    # inequality !=
    def __ne__(self, other: Any, /) -> "BooleanArray": ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]


@runtime_checkable
class NumericalArray[Scalar](BaseArray, SupportsVectorComparison[Scalar], Protocol):
    r"""Subclass of `ArrayKind` that supports numerical operations.

    Examples:
        - `numpy.ndarray`
        - `pandas.DataFrame`
        - `pandas.Index`
        - `pandas.Series`
        - `pandas.extensions.ExtensionArray`
        - `polars.Series`
        - `torch.Tensor`

    Counter-Examples:
        - `polars.DataFrame`  (does not support basic arithmetic)
        - `pyarrow.Array`  (does not support basic arithmetic)
        - `pyarrow.Table`  (does not support basic arithmetic)

    References:
        - This is a weak version of the Array API:
          https://data-apis.org/array-api/latest/API_specification/array_object.html
        - https://data-apis.org/dataframe-api/draft/index.html
        - https://numpy.org/devdocs/user/basics.interoperability.html
    """

    def all(self) -> BoolScalar: ...
    def any(self) -> BoolScalar: ...
    def min(self) -> Any: ...
    def max(self) -> Any: ...

    # region arithmetic operations -----------------------------------------------------
    # unary operations
    # absolute value abs()
    def __abs__(self) -> Self: ...
    # bitwise NOT ~
    def __invert__(self) -> Self: ...
    # negation -
    def __neg__(self) -> Self: ...
    # positive +
    def __pos__(self) -> Self: ...

    # FIXME: Possibly should look like
    #   def __add__[Z](self, other: Y | Vec[Y], /) -> Vec[Z]: ...
    #   where Y = SupportsRAdd[Scalar, Z] is a protocol with
    #   def __radd__(self, other: Scalar, /) -> Z: ...
    #   this would allow compatibility for timedelta/datetime.

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # + (addition)
    def __add__(self, other: Self | Scalar, /) -> Self: ...
    def __radd__(self, other: Self | Scalar, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | Scalar, /) -> Self: ...
    def __rsub__(self, other: Self | Scalar, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | Scalar, /) -> Self: ...
    def __rmul__(self, other: Self | Scalar, /) -> Self: ...
    # / (true division)
    def __truediv__(self, other: Self | Scalar, /) -> Self: ...
    def __rtruediv__(self, other: Self | Scalar, /) -> Self: ...
    # // (floor division)
    def __floordiv__(self, other: Self | Scalar, /) -> Self: ...
    def __rfloordiv__(self, other: Self | Scalar, /) -> Self: ...
    # ** (power)
    # NOTE: arrow/polars does not support complex data types!
    def __pow__(self, exponent: Self | float, /) -> Self: ...
    def __rpow__(self, base: Self | float, /) -> Self: ...
    # % (modulo)
    def __mod__(self, other: Self | Scalar | float, /) -> Self: ...
    def __rmod__(self, other: Self | Scalar | float, /) -> Self: ...
    # & (AND)
    def __and__(self, other: Self | Scalar, /) -> Self: ...
    def __rand__(self, other: Self | Scalar, /) -> Self: ...
    # | (OR)
    def __or__(self, other: Self | Scalar, /) -> Self: ...
    def __ror__(self, other: Self | Scalar, /) -> Self: ...
    # ^ (XOR)
    def __xor__(self, other: Self | Scalar, /) -> Self: ...
    def __rxor__(self, other: Self | Scalar, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------

    # region overload alternatives -----------------------------------------------------
    # >>> # + (addition)
    # >>> @overload
    # >>> def __add__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __add__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __radd__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __radd__(self, other: Scalar, /) -> Self: ...
    # >>> # - (subtraction)
    # >>> @overload
    # >>> def __sub__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __sub__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __rsub__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rsub__(self, other: Scalar, /) -> Self: ...
    # >>> # * (multiplication)
    # >>> @overload
    # >>> def __mul__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __mul__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __mul__(self, other: float, /) -> Self: ...
    # >>> @overload
    # >>> def __rmul__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rmul__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __rmul__(self, other: float, /) -> Self: ...
    # >>> # / (true division)
    # >>> @overload
    # >>> def __truediv__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __truediv__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __truediv__(self, other: int, /) -> Self: ...
    # >>> @overload
    # >>> def __rtruediv__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rtruediv__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __rtruediv__(self, other: int, /) -> Self: ...
    # >>> # // (floor division)
    # >>> # NOTE: complex types do not support floor division.
    # >>> @overload
    # >>> def __floordiv__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __floordiv__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __rfloordiv__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rfloordiv__(self, other: Scalar, /) -> Self: ...
    # >>> # ** (power)
    # >>> # NOTE: arrow/polars does not support complex data types!
    # >>> @overload
    # >>> def __pow__(self, exponent: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __pow__(self, exponent: float, /) -> Self: ...
    # >>> @overload
    # >>> def __rpow__(self, base: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rpow__(self, base: float, /) -> Self: ...
    # >>> # % (modulo)
    # >>> @overload
    # >>> def __mod__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __mod__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __mod__(self, other: float, /) -> Self: ...
    # >>> @overload
    # >>> def __rmod__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rmod__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __rmod__(self, other: float, /) -> Self: ...
    # >>> # & (AND)
    # >>> @overload
    # >>> def __and__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __and__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __and__(self, other: int, /) -> Self: ...
    # >>> @overload
    # >>> def __rand__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rand__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __rand__(self, other: int, /) -> Self: ...
    # >>> # | (OR)
    # >>> @overload
    # >>> def __or__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __or__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __or__(self, other: int, /) -> Self: ...
    # >>> @overload
    # >>> def __ror__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __ror__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __ror__(self, other: int, /) -> Self: ...
    # >>> # ^ (XOR)
    # >>> @overload
    # >>> def __xor__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __xor__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __xor__(self, other: int, /) -> Self: ...
    # >>> @overload
    # >>> def __rxor__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rxor__(self, other: Scalar, /) -> Self: ...
    # >>> @overload
    # >>> def __rxor__(self, other: int, /) -> Self: ...
    # endregion overload alternatives --------------------------------------------------

    # endregion arithmetic operations --------------------------------------------------


@runtime_checkable
class BooleanArray[T](
    # BaseArray,
    # SupportsVectorComparison[T | bool],
    Protocol,
):
    r"""Protocol for boolean array-like types supporting standard boolean operations."""

    # Using Protocol here to allow for different return types
    def __invert__(self) -> Self: ...
    def all(self) -> BoolScalar: ...
    def any(self) -> BoolScalar: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    def __and__(self, other: Self | T | bool, /) -> Self: ...
    def __rand__(self, other: Self | T | bool, /) -> Self: ...

    def __or__(self, other: Self | T | bool, /) -> Self: ...
    def __ror__(self, other: Self | T | bool, /) -> Self: ...

    def __xor__(self, other: Self | T | bool, /) -> Self: ...
    def __rxor__(self, other: Self | T | bool, /) -> Self: ...

    # endregion binary  operations -----------------------------------------------------

    # region comparison operations -----------------------------------------------------
    def __eq__(self, other: Self | T | Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __ne__(self, other: Self | T | Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __lt__(self, other: Self | T | Any, /) -> Self: ...
    def __le__(self, other: Self | T | Any, /) -> Self: ...
    def __gt__(self, other: Self | T | Any, /) -> Self: ...
    def __ge__(self, other: Self | T | Any, /) -> Self: ...

    # endregion comparison operations --------------------------------------------------


@runtime_checkable
class IntegerArray[T](
    # BaseArray,
    # SupportsVectorComparison[T | float],
    Protocol,
):
    r"""Protocol for integer array-like types supporting standard arithmetic operations."""

    def clip(self, lower: Any, upper: Any, /) -> Self: ...

    # aggregations
    def min(self) -> Self | T | int: ...
    def max(self) -> Self | T | int: ...

    def sum(self) -> Self | T | int: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # ~ (bitwise NOT)
    def __invert__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # + (addition)
    @overload
    def __add__(self, other: Self | T | int, /) -> Self: ...
    @overload
    def __add__(self, other: float, /) -> "FloatArray": ...
    @overload
    def __radd__(self, other: Self | T | int, /) -> Self: ...
    @overload
    def __radd__(self, other: float, /) -> "FloatArray": ...
    # def __add__(self, other: Self | T | int, /) -> Self: ...
    # def __radd__(self, other: Self | T | int, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | T | int, /) -> Self: ...
    def __rsub__(self, other: Self | T | int, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | T | int, /) -> Self: ...
    def __rmul__(self, other: Self | T | int, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | T | int, /) -> Self: ...
    def __rpow__(self, base: Self | T | int, /) -> Self: ...
    # // (floor division)
    def __floordiv__(self, other: Self | T | int, /) -> Self: ...
    def __rfloordiv__(self, other: Self | T | int, /) -> Self: ...
    # % (modulo)
    @overload
    def __mod__(self, other: Self | T | int, /) -> Self: ...
    @overload
    def __mod__(self, other: float, /) -> "FloatArray": ...
    @overload
    def __rmod__(self, other: Self | T | int, /) -> Self: ...
    @overload
    def __rmod__(self, other: float, /) -> "FloatArray": ...

    # FIXME: https://github.com/pytorch/pytorch/issues/155701
    # >>> # & (bitwise AND)
    # >>> def __and__(self, other: Self | T | int, /) -> Self: ...
    # >>> def __rand__(self, other: Self | T | int, /) -> Self: ...
    # >>> # | (bitwise OR)
    # >>> def __or__(self, other: Self | T | int, /) -> Self: ...
    # >>> def __ror__(self, other: Self | T | int, /) -> Self: ...
    # >>> # ^ (bitwise XOR)
    # >>> def __xor__(self, other: Self | T | int, /) -> Self: ...
    # >>> def __rxor__(self, other: Self | T | int, /) -> Self: ...
    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class FloatArray[T](
    # BaseArray,
    # SupportsVectorComparison[T | float],
    Protocol,
):
    r"""Protocol for floating-point array-like types supporting standard arithmetic operations."""

    @overload
    def round(self) -> Self: ...
    @overload
    def round(self, *, decimals: int) -> Self: ...
    def clip(self, lower: Any, upper: Any, /) -> Self: ...

    # aggregations
    def min(self) -> Self | T | float: ...
    def max(self) -> Self | T | float: ...

    def sum(self) -> Self | T | float: ...
    def mean(self) -> Self | T | float: ...
    def std(self) -> Self | T | float: ...
    def var(self) -> Self | T | float: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # + (addition)
    def __add__(self, other: Self | T | float, /) -> Self: ...
    def __radd__(self, other: Self | T | float, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | T | float, /) -> Self: ...
    def __rsub__(self, other: Self | T | float, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | T | float, /) -> Self: ...
    def __rmul__(self, other: Self | T | float, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | T | float, /) -> Self: ...
    def __rpow__(self, base: Self | T | float, /) -> Self: ...
    # / (true division)
    def __truediv__(self, other: Self | T | float, /) -> Self: ...
    def __rtruediv__(self, other: Self | T | float, /) -> Self: ...
    # // (floor division)
    def __floordiv__(self, other: Self | T | float, /) -> Self: ...
    def __rfloordiv__(self, other: Self | T | float, /) -> Self: ...

    # % (modulo)
    # FIXME:
    # def __mod__(self, other: Self | T | float, /) -> Self: ...
    # def __rmod__(self, other: Self | T | float, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class ComplexArray[T](
    # BaseArray,
    Protocol,
):
    r"""Protocol for complex array-like types supporting standard arithmetic operations."""

    # aggregations
    def sum(self) -> Self | T | complex: ...
    def mean(self) -> Self | T | complex: ...
    def std(self) -> FloatArray | FloatScalar: ...
    def var(self) -> FloatArray | FloatScalar: ...

    # absolute value abs()
    def __abs__(self) -> FloatArray[Any]: ...
    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # + (addition)
    def __add__(self, other: Self | T | complex, /) -> Self: ...
    def __radd__(self, other: Self | T | complex, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | T | complex, /) -> Self: ...
    def __rsub__(self, other: Self | T | complex, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | T | complex, /) -> Self: ...
    def __rmul__(self, other: Self | T | complex, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | T | complex, /) -> Self: ...
    def __rpow__(self, base: Self | T | complex, /) -> Self: ...
    # / (true division)
    def __truediv__(self, other: Self | T | complex, /) -> Self: ...
    def __rtruediv__(self, other: Self | T | complex, /) -> Self: ...

    # // (floor division) -- not supported for complex numbers, so omitted
    # % (modulo) -- not supported for complex numbers, so omitted
    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class TimedeltaArray[T: Any = DurationScalar](
    BaseArray,
    SupportsVectorComparison[T | timedelta],
    Protocol,
):
    r"""Protocol for timedelta array-like types supporting standard timedelta operations."""

    def min(self) -> Any | Self | T: ...
    def max(self) -> Any | Self | T: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # + (addition with timedelta)
    def __add__(self, other: Self | T | timedelta, /) -> Self: ...
    def __radd__(self, other: Self | T | timedelta, /) -> Self: ...
    # - (subtraction with timedelta)
    def __sub__(self, other: Self | T | timedelta, /) -> Self: ...
    def __rsub__(self, other: Self | T | timedelta, /) -> Self: ...
    # * (multiplication with int)
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...
    # // (floor division with int)
    def __floordiv__(self, other: int, /) -> Self: ...
    def __rfloordiv__(self, other: int, /) -> Self: ...
    # / (true division with int)
    def __truediv__(self, other: int, /) -> Self: ...
    def __rtruediv__(self, other: int, /) -> Self: ...


@runtime_checkable
class DatetimeArray[T: Any = TimestampScalar, Dual: TimedeltaArray = Any](
    BaseArray,
    SupportsVectorComparison[T | datetime],
    Protocol,
):
    r"""Protocol for timestamp array-like types supporting standard datetime operations."""

    def min(self) -> Any | Self | T: ...
    def max(self) -> Any | Self | T: ...

    # + (addition with timedelta)
    def __add__(self, other: Dual | timedelta, /) -> Self: ...
    def __radd__(self, other: Dual | timedelta, /) -> Self: ...
    # - (subtraction with datetime)
    def __sub__(self, other: Self | T | datetime, /) -> Dual: ...
    def __rsub__(self, other: Self | T | datetime, /) -> Dual: ...


@runtime_checkable
class NumericalSeries[Scalar](NumericalArray[Scalar], Protocol):
    r"""Protocol for numerical series.

    Series are per definition one dimensional, and have a unique data type.
    Notably, this differs with respect to `NumericalTensor` by not supporting tuple-indexing.
    Moreover, its Iterator and `__getitem__(int)` return scalars.

    Note:
        Multidimensional Tensors are by definition Series of Tensors.
        For instance, a 3-dimensional numpy array is a `NumericalSeries[NDArray]`.

    Examples:
        - `numpy.ndarray` (if 1d)
        - `pandas.Index`
        - `pandas.Series`
        - `pandas.extensions.ExtensionArray`
        - `polars.Series`
        - `torch.Tensor` (if 1d)

    Counter-Examples:
        - `pandas.DataFrame`
        - `polars.DataFrame`
    """

    @property
    def dtype(self) -> Any: ...
    def __iter__(self) -> Iterator[Scalar] | Iterator[Self]: ...

    # fmt: off
    @overload
    def __getitem__(self, key: int, /) -> Scalar | Self: ...
    @overload
    def __getitem__(self, key: slice | range | list[int] | Self, /) -> Self: ...
    # fmt: on


@runtime_checkable
class NumericalTensor[Scalar](NumericalArray[Scalar], Protocol):
    r"""Protocol for numerical tensors.

    Compared to `NumericalSeries`, tensors *can* have multiple dimensions, and
    must support more Indexing operations, In particular `...` (Ellipsis), and
    tuples of ints and/or slices.

    Examples:
        - `numpy.ndarray`
        - `pandas.Series`
        - `torch.Tensor`

    Counter-Examples:
        - `polars.Series`    (cannot be indexed with Ellipsis and tuple)
        - `polars.DataFrame` (cannot be indexed with Ellipsis and tuple)
    """

    @property
    def dtype(self) -> Any: ...
    @property
    def ndim(self) -> int: ...

    def __iter__(self) -> Iterator[Scalar] | Iterator[Self]: ...

    # matrix multiplication @
    def __matmul__(self, other: Self, /) -> Self: ...
    def __rmatmul__(self, other: Self, /) -> Self: ...

    # fmt: off
    @overload  # depending on Tensor Rank, can return Scalar or Tensor
    def __getitem__(self, key: int | tuple[int, ...], /) -> Scalar | Self: ...  # type: ignore[overload-overlap]  # pyright: ignore[reportOverlappingOverload]
    @overload
    def __getitem__(self, key: Self | MultiIndexer, /) -> Self: ...
    # fmt: on

    @overload
    def argmin(self, axis: None = ..., /) -> SupportsInt: ...
    @overload
    def argmin(self, axis: int, /) -> Self: ...

    @overload
    def argmax(self, axis: None = ..., /) -> SupportsInt: ...
    @overload
    def argmax(self, axis: int, /) -> Self: ...

    def argsort(self, axis: int = -1, /) -> Self: ...

    def clip(self, lower: Any, upper: Any, /) -> Self: ...
    def cumsum(self, axis: int, /) -> Scalar | Self: ...
    def cumprod(self, axis: int, /) -> Scalar | Self: ...
    def std(self, axis: Axis = ..., /) -> Scalar | Self: ...
    def var(self, axis: Axis = ..., /) -> Scalar | Self: ...

    def ravel(self) -> Self:
        r"""Return a flattened version of the tensor."""
        ...

    def take(self, indices: Any, /) -> Self:
        r"""Select elements from the array by index."""
        ...

    # NOTE: Disabled since pyright says numpy incompatible
    # def item(self) -> Scalar:
    #     r"""Return the scalar value the tensor if it only has a single element.
    #
    #     Otherwise, raises `ValueError`.
    #     """
    #     ...

    # region stupid overloads ----------------------------------------------------------
    # FIXME: https://github.com/python/typing/discussions/1782
    @overload
    def mean(self) -> Scalar | Self: ...
    @overload
    def mean(self, axis: Axis, /) -> Scalar | Self: ...

    @overload
    def sum(self) -> Self: ...
    @overload
    def sum(self, axis: Axis, /) -> Self: ...

    @overload
    def prod(self) -> Scalar | Self: ...
    @overload
    def prod(self, axis: int, /) -> Scalar | Self: ...

    @overload
    def round(self) -> Self: ...
    @overload
    def round(self, *, decimals: int) -> Self: ...

    @overload
    def squeeze(self) -> Self: ...
    @overload  # FIXME: https://github.com/pytorch/pytorch/issues/137422
    def squeeze(self, axis: int, /) -> Self: ...

    # endregion stupid overloads -------------------------------------------------------


@runtime_checkable
class MutableTensor[Scalar](NumericalTensor[Scalar], SupportsMutation, Protocol):
    r"""Subclass of `NumericalTensor` that supports inplace operations.

    Examples:
        - `numpy.ndarray`
        - `pandas.Series`
        - `torch.Tensor`

    Counter-Examples:
        - `pandas.Index`     (does not support inplace operations)
        - `pandas.extensions.ExtensionArray`  (does not support inplace operations)
        - `polars.DataFrame` (does not support inplace operations)
        - `polars.Series`    (does not support inplace operations)
        - `pyarrow.Array`    (does not support inplace operations)
        - `pyarrow.Table`    (does not support inplace operations)
    """
