r"""Protocol for scalars.

Note:
    We do not provide protocols for string and byte types, since `np.str_` has some
    unintuitive behavior. For instance `np.string_("x") + np.string_("y")` returns
    the plain python string `"xy"`, which is not a numpy string.

Note:
    Boolean Scalars lack the `__invert__` method, because `~True` is `-2`, which is not a boolean.
    This method will get deprecated anyways: https://discuss.python.org/t/bool-deprecation/62232
"""

__all__ = [
    # Protocols
    "SupportsBool",
    "BaseScalar",
    "OrderedScalar",
    "AdditiveScalar",
    # concrete data types
    "RealScalar",
    "BoolScalar",
    "ComplexScalar",
    "FloatScalar",
    "IntScalar",
    "DurationScalar",
    "TimestampScalar",
]

from typing import (
    Any,
    Protocol,
    Self,
    SupportsFloat,
    SupportsInt,
    overload,
    runtime_checkable,
)


# region generic scalars ---------------------------------------------------------------
@runtime_checkable
class BaseScalar(Protocol):
    r"""Protocol for scalars.

    Note:
        All scalar types must be hashable.
    """

    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> "BoolScalar": ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __ne__(self, other: object, /) -> "BoolScalar": ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]


@runtime_checkable
class OrderedScalar(BaseScalar, Protocol):
    r"""Protocol for scalars that support inequality comparisons.

    Examples:
        - `bool`, `int`, `float`, `datetime`, `timedelta`, `tuple`, `str`

    Counter-Examples:
        - `complex` (not ordered)
        - `list` (not hashable)
    """

    def __ge__(self, other: Self | Any, /) -> "BoolScalar": ...
    def __gt__(self, other: Self | Any, /) -> "BoolScalar": ...
    def __le__(self, other: Self | Any, /) -> "BoolScalar": ...
    def __lt__(self, other: Self | Any, /) -> "BoolScalar": ...


@runtime_checkable
class AdditiveScalar(BaseScalar, Protocol):
    r"""Protocol for scalars that support addition and subtraction.

    Examples:
        - `int`, `float`, `complex`, `timedelta`

    Counter-Examples:
        - `bool` (does not support `__pos__` and `__neg__`)
        - `datetime.datetime` (does not support addition with datetime)
    """

    # unary operations
    # NOTE: __abs__ disabled due to complex numbers
    # def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # binary operations
    # + (addition)
    def __add__(self, other: Self, /) -> Self: ...
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self, /) -> Self: ...
    def __rsub__(self, other: Self, /) -> Self: ...


class RealScalar(OrderedScalar, Protocol):
    r"""Protocol for ordered scalars that support integer multiplication and division.

    Examples:
        - `int`, `float`,`timedelta`
    """

    def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # + (addition)
    def __add__(self, other: Self, /) -> Self: ...
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self, /) -> Self: ...
    def __rsub__(self, other: Self, /) -> Self: ...
    # binary operations
    # * (multiplication)
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...
    # / (division)
    def __truediv__(self, other: Self, /) -> "FloatScalar": ...
    def __floordiv__(self, other: Self, /) -> "FloatScalar": ...


# endregion generic scalars ------------------------------------------------------------


# region concrete data types -----------------------------------------------------------
@runtime_checkable
class SupportsBool(Protocol):
    r"""Protocol for types that support boolean operations."""

    def __bool__(self) -> bool: ...


@runtime_checkable
class BoolScalar(OrderedScalar, Protocol):
    r"""Protocol for boolean scalars.

    Note:
        Crucially, `BooleanScalar` objects must be convertible to `bool` via the `__bool__` method.
        The `__invert__` method is not included, as `~True` is `-2`, which is not a boolean.
    """

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...

    # unary operations
    # NOTE: __invert__ disabled, because ~True == -2
    # def __invert__(self) -> Self: ...

    # region comparison operations -----------------------------------------------------
    def __eq__(self, other: Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __ne__(self, other: Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __lt__(self, other: Any, /) -> Self: ...
    def __le__(self, other: Any, /) -> Self: ...
    def __gt__(self, other: Any, /) -> Self: ...
    def __ge__(self, other: Any, /) -> Self: ...

    # endregion comparison operations---------------------------------------------------

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # & (and)
    def __and__(self, other: Self | bool, /) -> Self: ...
    def __rand__(self, other: Self | bool, /) -> Self: ...
    # | (or)
    def __or__(self, other: Self | bool, /) -> Self: ...
    def __ror__(self, other: Self | bool, /) -> Self: ...
    # ^ (xor)
    def __xor__(self, other: Self | bool, /) -> Self: ...
    def __rxor__(self, other: Self | bool, /) -> Self: ...

    # >>> # & (and)
    # >>> @overload
    # >>> def __and__(self, other: bool, /) -> Self: ...
    # >>> @overload
    # >>> def __and__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rand__(self, other: bool, /) -> Self: ...
    # >>> @overload
    # >>> def __rand__(self, other: Self, /) -> Self: ...
    # >>> # | (or)
    # >>> @overload
    # >>> def __or__(self, other: bool, /) -> Self: ...
    # >>> @overload
    # >>> def __or__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __ror__(self, other: bool, /) -> Self: ...
    # >>> @overload
    # >>> def __ror__(self, other: Self, /) -> Self: ...
    # >>> # ^ (xor)
    # >>> @overload
    # >>> def __xor__(self, other: bool, /) -> Self: ...
    # >>> @overload
    # >>> def __xor__(self, other: Self, /) -> Self: ...
    # >>> @overload
    # >>> def __rxor__(self, other: bool, /) -> Self: ...
    # >>> @overload
    # >>> def __rxor__(self, other: Self, /) -> Self: ...

    # endregion binary operations-------------------------------------------------------


@runtime_checkable
class IntScalar(OrderedScalar, Protocol):
    r"""Protocol for integer scalars."""

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __float__(self) -> float: ...

    # unary operations
    def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # >>> # + (addition)
    # >>> def __add__(self, other: Self | int, /) -> Self: ...
    # >>> def __radd__(self, other: Self | int, /) -> Self: ...
    # >>> # - (subtraction)
    # >>> def __sub__(self, other: Self | int, /) -> Self: ...
    # >>> def __rsub__(self, other: Self | int, /) -> Self: ...
    # >>> # * (multiplication)
    # >>> def __mul__(self, other: Self | int, /) -> Self: ...
    # >>> def __rmul__(self, other: Self | int, /) -> Self: ...
    # >>> # ** (power)
    # >>> def __pow__(self, exponent: Self | int, /) -> Self: ...
    # >>> def __rpow__(self, base: Self | int, /) -> Self: ...
    # >>> # % (modulo)
    # >>> def __mod__(self, other: Self | int, /) -> Self: ...
    # >>> def __rmod__(self, other: Self | int, /) -> Self: ...
    # >>> # // (floor division)
    # >>> def __floordiv__(self, other: Self | int, /) -> Self: ...
    # >>> def __rfloordiv__(self, other: Self | int, /) -> Self: ...
    # >>> # / (division)
    # >>> def __truediv__(self, other: Self | int, /) -> SupportsFloat: ...
    # >>> def __rtruediv__(self, other: Self | int, /) -> SupportsFloat: ...

    # + (addition)
    @overload
    def __add__(self, other: int, /) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: int, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    @overload
    def __sub__(self, other: int, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: int, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    @overload
    def __mul__(self, other: int, /) -> Self: ...
    @overload
    def __mul__(self, other: Self, /) -> Self: ...
    @overload
    def __rmul__(self, other: int, /) -> Self: ...
    @overload
    def __rmul__(self, other: Self, /) -> Self: ...
    # ** (power)
    # NOTE: mypy breaks comparing to int.__pow__ (literal overload)
    @overload
    def __pow__(self, exponent: int, /) -> Self: ...
    @overload
    def __pow__(self, exponent: Self, /) -> Self: ...
    @overload
    def __rpow__(self, base: int, /) -> Self: ...
    @overload
    def __rpow__(self, base: Self, /) -> Self: ...
    # % (modulo)
    # NOTE: mypy breaks comparing to numpy.int64.__mod__ (bool overload)
    @overload
    def __mod__(self, other: int, /) -> Self: ...
    @overload
    def __mod__(self, other: Self, /) -> Self: ...
    @overload
    def __rmod__(self, other: int, /) -> Self: ...
    @overload
    def __rmod__(self, other: Self, /) -> Self: ...
    # // (floor division)
    @overload
    def __floordiv__(self, other: int, /) -> Self: ...
    @overload
    def __floordiv__(self, other: Self, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: int, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: Self, /) -> Self: ...
    # / (division)
    @overload
    def __truediv__(self, other: int, /) -> SupportsFloat: ...
    @overload
    def __truediv__(self, other: Self, /) -> SupportsFloat: ...
    @overload
    def __rtruediv__(self, other: int, /) -> SupportsFloat: ...
    @overload
    def __rtruediv__(self, other: Self, /) -> SupportsFloat: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class FloatScalar(OrderedScalar, Protocol):
    r"""Protocol for floating point scalars."""

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...

    # unary operations
    # abs() (absolute value)
    def __abs__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # + (positive)
    def __pos__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # >>> # + (addition)
    # >>> def __add__(self, other: Self | float, /) -> Self: ...
    # >>> def __radd__(self, other: Self | float, /) -> Self: ...
    # >>> # - (subtraction)
    # >>> def __sub__(self, other: Self | float, /) -> Self: ...
    # >>> def __rsub__(self, other: Self | float, /) -> Self: ...
    # >>> # * (multiplication)
    # >>> def __mul__(self, other: Self | float, /) -> Self: ...
    # >>> def __rmul__(self, other: Self | float, /) -> Self: ...
    # >>> # / (division)
    # >>> def __truediv__(self, other: Self | float, /) -> Self: ...
    # >>> def __rtruediv__(self, other: Self | float, /) -> Self: ...
    # >>> # ** (power)
    # >>> def __pow__(self, exponent: Self | float, /) -> Self: ...
    # >>> def __rpow__(self, base: Self | float, /) -> Self: ...
    # >>> # // (floor division)
    # >>> def __floordiv__(self, other: Self | float, /) -> Self: ...
    # >>> def __rfloordiv__(self, other: Self | float, /) -> Self: ...
    # >>> # % (modulo)
    # >>> def __mod__(self, other: Self | float, /) -> Self: ...
    # >>> def __rmod__(self, other: Self | float, /) -> Self: ...

    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __add__(self, other: float, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: float, /) -> Self: ...
    # - (subtraction)
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __sub__(self, other: float, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: float, /) -> Self: ...
    # * (multiplication)
    @overload
    def __mul__(self, other: Self, /) -> Self: ...
    @overload
    def __mul__(self, other: float, /) -> Self: ...
    @overload
    def __rmul__(self, other: Self, /) -> Self: ...
    @overload
    def __rmul__(self, other: float, /) -> Self: ...
    # / (division)
    @overload
    def __truediv__(self, other: Self, /) -> Self: ...
    @overload
    def __truediv__(self, other: float, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: Self, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: float, /) -> Self: ...
    # ** (power)
    @overload
    def __pow__(self, exponent: Self, /) -> Self: ...
    @overload
    def __pow__(self, exponent: float, /) -> Self: ...
    @overload
    def __rpow__(self, base: Self, /) -> Self: ...
    @overload
    def __rpow__(self, base: float, /) -> Self: ...
    # // (floor division)
    @overload
    def __floordiv__(self, other: Self, /) -> Self: ...
    @overload
    def __floordiv__(self, other: float, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: Self, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: float, /) -> Self: ...
    # % (modulo)
    @overload
    def __mod__(self, other: Self, /) -> Self: ...
    @overload
    def __mod__(self, other: float, /) -> Self: ...
    @overload
    def __rmod__(self, other: Self, /) -> Self: ...
    @overload
    def __rmod__(self, other: float, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class ComplexScalar(BaseScalar, Protocol):
    r"""Protocol for complex scalars."""

    # @property
    # def imag(self) -> Self: ...
    # @property
    # def real(self) -> Self: ...

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __complex__(self) -> complex: ...

    # unary operations
    def __abs__(self) -> SupportsFloat: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # >>> # + (addition)
    # >>> def __add__(self, other: Self | complex, /) -> Self: ...
    # >>> def __radd__(self, other: Self | complex, /) -> Self: ...
    # >>> # - (subtraction)
    # >>> def __sub__(self, other: Self | complex, /) -> Self: ...
    # >>> def __rsub__(self, other: Self | complex, /) -> Self: ...
    # >>> # * (multiplication)
    # >>> def __mul__(self, other: Self | complex, /) -> Self: ...
    # >>> def __rmul__(self, other: Self | complex, /) -> Self: ...
    # >>> # / (division)
    # >>> def __truediv__(self, other: Self | complex, /) -> Self: ...
    # >>> def __rtruediv__(self, other: Self | complex, /) -> Self: ...
    # >>> # ** (power)
    # >>> def __pow__(self, exponent: Self | complex, /) -> Self: ...
    # >>> def __rpow__(self, base: Self | complex, /) -> Self: ...
    # + (addition)
    @overload
    def __add__(self, other: complex, /) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: complex, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    @overload
    def __sub__(self, other: complex, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: complex, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    @overload
    def __mul__(self, other: complex, /) -> Self: ...
    @overload
    def __mul__(self, other: Self, /) -> Self: ...
    @overload
    def __rmul__(self, other: complex, /) -> Self: ...
    @overload
    def __rmul__(self, other: Self, /) -> Self: ...
    # / (division)
    @overload
    def __truediv__(self, other: complex, /) -> Self: ...
    @overload
    def __truediv__(self, other: Self, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: complex, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: Self, /) -> Self: ...
    # ** (power)
    @overload
    def __pow__(self, exponent: complex, /) -> Self: ...
    @overload
    def __pow__(self, exponent: Self, /) -> Self: ...
    @overload
    def __rpow__(self, base: complex, /) -> Self: ...
    @overload
    def __rpow__(self, base: Self, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class DurationScalar(OrderedScalar, Protocol):
    r"""Time delta provides several arithmetical operations."""

    # unary operations
    # def __bool__(self) -> bool: ...
    def __abs__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __neg__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # + (addition)
    def __add__(self, other: Self, /) -> Self: ...
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    # FIXME: broken with numpy. https://github.com/numpy/numpy/issues/28257
    def __sub__(self, other: Self, /) -> Self: ...
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...
    # / (division)
    def __truediv__(self, other: Self, /) -> SupportsFloat: ...

    # @overload
    # def __truediv__(self, other: Self, /) -> float: ...
    # @overload
    # def __truediv__(self, other: float, /) -> Self: ...

    # // (floor division)
    def __floordiv__(self, other: Self, /) -> SupportsInt: ...

    # @overload
    # def __floordiv__(self, other: Self, /) -> int: ...
    # @overload
    # def __floordiv__(self, other: int, /) -> Self: ...

    # % (modulo)
    def __mod__(self, other: Self, /) -> Self: ...

    # NOTE: __rmod__ missing on fallback pydatetime
    # def __rmod__(self, other: Self, /) -> Self: ...

    # divmod
    def __divmod__(self, other: Self, /) -> tuple[SupportsInt, Self]: ...

    # NOTE: __rdivmod__ missing on fallback pydatetime
    # def __rdivmod__(self, other: Self, /) -> tuple[SupportsInt, Self]: ...


@runtime_checkable
class TimestampScalar[TD: DurationScalar](OrderedScalar, Protocol):
    r"""TimeStamps can be compared and subtracted."""

    def __add__(self, other: TD, /) -> Self: ...
    def __radd__(self, other: TD, /) -> Self: ...

    # FIXME: broken with numpy. https://github.com/numpy/numpy/issues/28257
    @overload
    def __sub__(self, other: Self, /) -> TD: ...
    @overload
    def __sub__(self, other: TD, /) -> Self: ...

    # FIXME: __rsub__ missing on fallback pydatetime
    # @overload
    # def __rsub__(self, other: Self, /) -> TD: ...
    # @overload
    # def __rsub__(self, other: TD, /) -> Self: ...


# endregion concrete data types --------------------------------------------------------
