r"""Protocols for linear algebra types."""

__all__ = [
    # Comparison Protocols
    # Generic Protocols
    "BaseArray",
    "ArraySupportsEquality",
    "ArraySupportsComparison",
    "ArrayType",
    "TimeLikeArray",
    "SpanLikeArray",
    # Python scalar compatible Array Protocols
    "BooleanArray",
    "IntegerArray",
    "FloatArray",
    "ComplexArray",
    "TimedeltaArray",
    "DatetimeArray",
]

from datetime import datetime, timedelta
from typing import (
    TYPE_CHECKING,
    Any,
    Never,
    Protocol,
    Self,
    overload,
    runtime_checkable,
)

from numpy.typing import NDArray

from .mixins import (
    SupportsArray,
    SupportsComparison,
    SupportsDtype,
    SupportsEquality,
    SupportsShape,
)
from .scalars import (
    BoolScalar,
    ComplexScalar,
    FloatScalar,
    IntScalar,
    SpanLikeScalar,
    TimeLikeScalar,
)


@runtime_checkable
class ArrayType[V](Protocol):
    r"""An n-dimensional container type convertible to a numpy array.

    Examples:
        - `numpy.ndarray`
        - `pandas.DataFrame`
        - `pandas.Series`
        - `pandas.extensions.ExtensionArray`
        - `polars.DataFrame`
        - `polars.Series`
        - `pyarrow.Array`
        - `pyarrow.Table`
        - `torch.Tensor`

    References:
        - https://docs.python.org/3/c-api/buffer.html
        - https://numpy.org/doc/stable/reference/arrays.interface.html
        - https://numpy.org/devdocs/user/basics.interoperability.html
    """

    @property
    def shape(self) -> tuple[int, ...]: ...
    def __array__(self) -> NDArray: ...
    def __len__(self) -> int: ...


@runtime_checkable
class BaseArray(
    SupportsArray,
    SupportsDtype,
    SupportsShape,
    Protocol,
):
    r"""Protocol for a ND-array of homogeneous data type."""

    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> Any: ...
    def __array__(self) -> NDArray: ...  # removal candidate
    def __len__(self) -> int: ...
    def __contains__(self, element: Any, /) -> bool: ...
    def __getitem__(self, key: Any, /) -> Self | Any: ...


@runtime_checkable
class ArraySupportsEquality[
    ComparableT,  # contravariant
    BoolA: BooleanArray = BooleanArray,
](
    BaseArray,
    SupportsEquality[ComparableT, BoolA],
    Protocol,
):
    r"""Protocol for array-like types supporting standard equality operations."""


@runtime_checkable
class ArraySupportsComparison[
    ComparableT,  # contravariant
    BoolA: BooleanArray = BooleanArray,
](
    BaseArray,
    SupportsEquality[ComparableT, BoolA],
    SupportsComparison[ComparableT, BoolA],
    Protocol,
):
    r"""Protocol for array-like types supporting standard comparison operations."""


@runtime_checkable
class BooleanArray[BoolT](
    ArraySupportsEquality,
    Protocol,
):
    r"""Protocol for boolean array-like types supporting standard boolean operations."""

    def __eq__(self, other: Any, /) -> Self | Any: ...  # type: ignore[override]
    def __ne__(self, other: Any, /) -> Self | Any: ...  # type: ignore[override]

    def __invert__(self) -> Self: ...
    def all(self) -> Self | BoolScalar | Any: ...
    def any(self) -> Self | BoolScalar | Any: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.

    if not TYPE_CHECKING and False:  # 3x overloads per binary operator
        # & (bitwise AND)
        def __and__(self, other: Self | BoolT | bool, /) -> Self: ...
        def __rand__(self, other: Self | BoolT | bool, /) -> Self: ...
        # | (bitwise OR)
        def __or__(self, other: Self | BoolT | bool, /) -> Self: ...
        def __ror__(self, other: Self | BoolT | bool, /) -> Self: ...
        # ^ (bitwise XOR)
        def __xor__(self, other: Self | BoolT | bool, /) -> Self: ...
        def __rxor__(self, other: Self | BoolT | bool, /) -> Self: ...

    if not TYPE_CHECKING and False:  # 2x overloads per binary operator
        # & (bitwise AND)
        @overload
        def __and__(self, other: BoolT | bool, /) -> Self: ...
        @overload
        def __and__(self, other: Self, /) -> Self: ...
        @overload
        def __rand__(self, other: BoolT | bool, /) -> Self: ...
        @overload
        def __rand__(self, other: Self, /) -> Self: ...

        # | (bitwise OR)
        @overload
        def __or__(self, other: BoolT | bool, /) -> Self: ...
        @overload
        def __or__(self, other: Self, /) -> Self: ...
        @overload
        def __ror__(self, other: BoolT | bool, /) -> Self: ...
        @overload
        def __ror__(self, other: Self, /) -> Self: ...

        # ^ (bitwise XOR)
        @overload
        def __xor__(self, other: BoolT | bool, /) -> Self: ...
        @overload
        def __xor__(self, other: Self, /) -> Self: ...
        @overload
        def __rxor__(self, other: BoolT | bool, /) -> Self: ...
        @overload
        def __rxor__(self, other: Self, /) -> Self: ...

    if True:  # 3x overloads per binary operator
        # & (bitwise AND)
        @overload
        def __and__(self, other: bool, /) -> Self: ...
        @overload
        def __and__(self, other: BoolT, /) -> Self: ...
        @overload
        def __and__(self, other: Self, /) -> Self: ...
        @overload
        def __rand__(self, other: bool, /) -> Self: ...
        @overload
        def __rand__(self, other: BoolT, /) -> Self: ...
        @overload
        def __rand__(self, other: Self, /) -> Self: ...
        # | (bitwise OR)
        @overload
        def __or__(self, other: bool, /) -> Self: ...
        @overload
        def __or__(self, other: BoolT, /) -> Self: ...
        @overload
        def __or__(self, other: Self, /) -> Self: ...
        @overload
        def __ror__(self, other: bool, /) -> Self: ...
        @overload
        def __ror__(self, other: BoolT, /) -> Self: ...
        @overload
        def __ror__(self, other: Self, /) -> Self: ...
        # ^ (bitwise XOR)
        @overload
        def __xor__(self, other: bool, /) -> Self: ...
        @overload
        def __xor__(self, other: BoolT, /) -> Self: ...
        @overload
        def __xor__(self, other: Self, /) -> Self: ...
        @overload
        def __rxor__(self, other: bool, /) -> Self: ...
        @overload
        def __rxor__(self, other: BoolT, /) -> Self: ...
        @overload
        def __rxor__(self, other: Self, /) -> Self: ...

    # endregion binary  operations -----------------------------------------------------


@runtime_checkable
class IntegerArray[IntT, CompatT = Any](
    ArraySupportsComparison[float],
    Protocol,
):
    r"""Protocol for integer array-like types supporting standard arithmetic operations."""

    def clip(self, lower: Any, upper: Any, /) -> Self: ...

    # aggregations
    def min(self) -> Self | IntScalar | Any: ...
    def max(self) -> Self | IntScalar | Any: ...
    def sum(self) -> Self | IntScalar | Any: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # ~ (bitwise NOT)
    def __invert__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # + (addition)
    def __add__(self, other: Self | IntT | int, /) -> Self: ...
    def __radd__(self, other: Self | IntT | int, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | IntT | int, /) -> Self: ...
    def __rsub__(self, other: Self | IntT | int, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | IntT | int, /) -> Self: ...
    def __rmul__(self, other: Self | IntT | int, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | IntT | int, /) -> Self: ...
    def __rpow__(self, base: Self | IntT | int, /) -> Self: ...
    # // (floor division)
    def __floordiv__(self, other: Self | IntT | int, /) -> Self: ...
    def __rfloordiv__(self, other: Self | IntT | int, /) -> Self: ...
    # % (modulo)
    def __mod__(self, other: Self | IntT | int, /) -> Self: ...
    def __rmod__(self, other: Self | IntT | int, /) -> Self: ...
    # & (bitwise AND)
    def __and__(self, other: Self | IntT | int, /) -> Self: ...
    def __rand__(self, other: Self | IntT | int, /) -> Self: ...
    # | (bitwise OR)
    def __or__(self, other: Self | IntT | int, /) -> Self: ...
    def __ror__(self, other: Self | IntT | int, /) -> Self: ...
    # ^ (bitwise XOR)
    def __xor__(self, other: Self | IntT | int, /) -> Self: ...
    def __rxor__(self, other: Self | IntT | int, /) -> Self: ...

    # @overload
    # def __add__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __add__(self, other: float, /) -> "FloatArray": ...
    # @overload
    # def __radd__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __radd__(self, other: float, /) -> "FloatArray": ...
    # @overload
    # def __mod__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __mod__(self, other: float, /) -> "FloatArray": ...
    # @overload
    # def __rmod__(self, other: Self | T | int, /) -> Self: ...
    # @overload
    # def __rmod__(self, other: float, /) -> "FloatArray": ...
    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class FloatArray[
    FloatT,  # (invariant): the float type of the array elements
    CompatT = Any,  # (contra): the compatible type for binary operations
    # we artificially lower bound CompaT to float by always using "CompatT | float"
](
    ArraySupportsComparison[CompatT | float],
    Protocol,
):
    r"""Protocol for floating-point array-like types supporting standard arithmetic operations."""

    @overload
    def round(self) -> Self: ...
    @overload
    def round(self, *, decimals: int) -> Self: ...
    def clip(self, lower: Any, upper: Any, /) -> Self: ...

    # aggregations
    def min(self) -> Self | FloatT | Any: ...
    def max(self) -> Self | FloatT | Any: ...
    def mean(self) -> Self | FloatT | Any: ...
    def sum(self) -> Self | FloatT | Any: ...
    def std(self) -> Self | FloatT | Any: ...
    def var(self) -> Self | FloatT | Any: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # + (addition)
    def __add__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    def __radd__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    def __rsub__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    def __rmul__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | FloatT | CompatT | float, /) -> Self: ...
    def __rpow__(self, base: Self | FloatT | CompatT | float, /) -> Self: ...
    # / (true division)
    def __truediv__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    def __rtruediv__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    # // (floor division)
    def __floordiv__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    def __rfloordiv__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    # % (modulo)
    def __mod__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...
    def __rmod__(self, other: Self | FloatT | CompatT | float, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class ComplexArray[ComplexT](
    BaseArray,
    Protocol,
):
    r"""Protocol for complex array-like types supporting standard arithmetic operations."""

    # aggregations
    def sum(self) -> Self | ComplexScalar | Any: ...
    def mean(self) -> Self | ComplexScalar | Any: ...
    def std(self) -> FloatArray | FloatScalar: ...
    def var(self) -> FloatArray | FloatScalar: ...

    # absolute value abs()
    def __abs__(self) -> FloatArray: ...
    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # + (addition)
    def __add__(self, other: Self | ComplexT | complex, /) -> Self: ...
    def __radd__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self | ComplexT | complex, /) -> Self: ...
    def __rsub__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: Self | ComplexT | complex, /) -> Self: ...
    def __rmul__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # ** (power)
    def __pow__(self, exponent: Self | ComplexT | complex, /) -> Self: ...
    def __rpow__(self, base: Self | ComplexT | complex, /) -> Self: ...
    # / (true division)
    def __truediv__(self, other: Self | ComplexT | complex, /) -> Self: ...
    def __rtruediv__(self, other: Self | ComplexT | complex, /) -> Self: ...

    # // (floor division) -- not supported for complex numbers, so omitted
    # % (modulo) -- not supported for complex numbers, so omitted
    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class SpanLikeArray[SpanT](
    ArraySupportsComparison[SpanT],
    Protocol,
):
    r"""Protocol for timedelta array-like types supporting standard timedelta operations."""

    def min(self) -> Self | SpanLikeScalar | Any: ...
    def max(self) -> Self | SpanLikeScalar | Any: ...

    # + (positive)
    def __pos__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # absolute value abs()
    def __abs__(self) -> Self: ...

    # # + (addition)
    # def __add__(self, other: Self | SpanT, /) -> Self: ...
    # def __radd__(self, other: Self | SpanT, /) -> Self: ...
    # # - (subtraction)
    # def __sub__(self, other: Self | SpanT, /) -> Self: ...
    # def __rsub__(self, other: Self | SpanT, /) -> Self: ...
    # # * (multiplication)
    # def __mul__(self, other: int, /) -> Self: ...
    # def __rmul__(self, other: int, /) -> Self: ...

    # + (addition)
    @overload
    def __add__(self, other: SpanT, /) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: SpanT, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    @overload
    def __sub__(self, other: SpanT, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: SpanT, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...
    # / (division)
    @overload
    def __truediv__(self, other: Self | SpanT, /) -> FloatArray: ...
    @overload  # NOTE: 'Self | Any' to fix numpy overload issue
    def __truediv__(self, other: int, /) -> Self | Any: ...

    # FIXME: disabled since not supported by all implementations
    # # // (floor division)
    # @overload
    # def __floordiv__(self, other: int, /) -> Self: ...
    # @overload
    # def __floordiv__(self, other: Self | T, /) -> IntegerArray: ...
    # # % (modulo)
    # def __mod__(self, other: Self, /) -> Self: ...
    # # divmod
    # def __divmod__(self, other: Self | T, /) -> tuple[IntegerArray, Self]: ...


@runtime_checkable
class TimedeltaArray[SpanT](
    SpanLikeArray[SpanT | timedelta],
    Protocol,
):
    r"""Protocol for timedelta array-like types supporting standard timedelta operations."""


@runtime_checkable
class TimeLikeArray[
    TimeT,
    SpanT = Never,
    DualT: SpanLikeArray = Never,
](
    ArraySupportsComparison[TimeT],
    Protocol,
):
    r"""Protocol for timestamp array-like types supporting standard datetime operations."""

    def min(self) -> Self | TimeLikeScalar | Any: ...
    def max(self) -> Self | TimeLikeScalar | Any: ...

    # + (addition with timedelta)
    @overload
    def __add__(self, other: SpanT, /) -> Self: ...
    @overload
    def __add__(self, other: DualT, /) -> Self: ...
    @overload
    def __radd__(self, other: SpanT, /) -> Self: ...
    @overload
    def __radd__(self, other: DualT, /) -> Self: ...
    # - (subtraction with datetime)
    @overload
    def __sub__(self, other: TimeT, /) -> DualT: ...
    @overload
    def __sub__(self, other: Self, /) -> DualT: ...

    # + (addition with timedelta)
    # def __add__(self, other: DualT | SpanT, /) -> Self: ...
    # def __radd__(self, other: DualT | SpanT, /) -> Self: ...

    # - (subtraction with datetime)
    # def __sub__(self, other: Self | TimeT, /) -> DualT: ...

    # def __rsub__(self, other: Self | TimeT, /) -> DualArrayT: ...


@runtime_checkable
class DatetimeArray[
    TimeT,
    SpanT = Any,
    DualT: TimedeltaArray = Any,
](
    TimeLikeArray[TimeT | datetime, SpanT | timedelta, DualT],
    Protocol,
):
    r"""Protocol for datetime array-like types supporting standard datetime operations."""
