r"""Protocol for scalars.

Note:
    We do not provide protocols for string and byte types, since `np.str_` has some
    unintuitive behavior. For instance `np.string_("x") + np.string_("y")` returns
    the plain python string `"xy"`, which is not a numpy string.

Note:
    Boolean Scalars lack the `__invert__` method, because `~True` is `-2`, which is not a boolean.
    This method will get deprecated anyways: https://discuss.python.org/t/bool-deprecation/62232
"""

__all__ = [
    # Type Aliases
    "PythonScalar",
    # Protocols
    "ScalarType",
    "OrderedScalar",
    "AdditiveScalar",
    "RealScalar",
    "SpanLikeScalar",
    "TimeLikeScalar",
    # concrete data types
    "BoolScalar",
    "IntScalar",
    "FloatScalar",
    "ComplexScalar",
    "DatetimeScalar",
    "TimedeltaScalar",
]

from datetime import datetime, timedelta
from typing import (
    Any,
    Protocol,
    Self,
    SupportsFloat,
    overload,
    runtime_checkable,
)

from numerical_types.mixins import (
    SupportsComparison,
    SupportsEquality,
)

# region Scalar Type Aliases -----------------------------------------------------------
type PythonScalar = bool | int | float | complex | str | bytes | datetime | timedelta
r"""Type Alias for Python scalars."""
# endregion Scalar Type Aliases --------------------------------------------------------


# region generic scalars ---------------------------------------------------------------
@runtime_checkable
class ScalarType[BoolT: BoolScalar](
    SupportsEquality[BoolT],
    Protocol,
):
    r"""Protocol for scalars.

    Note:
        All scalar types must be hashable.
    """

    def __hash__(self) -> int: ...


@runtime_checkable
class OrderedScalar[ComparableT, BoolT: BoolScalar = BoolScalar](
    ScalarType[BoolT],
    SupportsComparison[ComparableT, BoolT],
    Protocol,
):
    r"""Protocol for scalars that support inequality comparisons.

    Examples:
        - `bool`, `int`, `float`, `datetime`, `timedelta`, `tuple`, `str`

    Counter-Examples:
        - `complex` (not ordered)
        - `list` (not hashable)
    """

    # comparisons
    # def __ge__(self, other: Self | ComparableT, /) -> BoolScalar: ...
    # def __gt__(self, other: Self | ComparableT, /) -> BoolScalar: ...
    # def __le__(self, other: Self | ComparableT, /) -> BoolScalar: ...
    # def __lt__(self, other: Self | ComparableT, /) -> BoolScalar: ...


@runtime_checkable
class AdditiveScalar(ScalarType, Protocol):
    r"""Protocol for scalars that support addition and subtraction.

    Examples:
        - `int`, `float`, `complex`, `timedelta`

    Counter-Examples:
        - `bool` (does not support `__pos__` and `__neg__`)
        - `datetime.datetime` (does not support addition with datetime)
    """

    # unary operations
    # NOTE: __abs__ disabled due to complex numbers
    # def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # binary operations
    # + (addition)
    def __add__(self, other: Self, /) -> Self: ...
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self, /) -> Self: ...
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication with int)
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...


@runtime_checkable
class RealScalar(OrderedScalar, Protocol):
    r"""Protocol for ordered scalars that support  multiplication and division.

    Examples:
        - `int`, `float`,`timedelta`
    """

    def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # + (addition)
    def __add__(self, other: Self, /) -> Self: ...
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    def __sub__(self, other: Self, /) -> Self: ...
    def __rsub__(self, other: Self, /) -> Self: ...
    # binary operations
    # * (multiplication)
    def __mul__(self, other: float, /) -> Self: ...
    def __rmul__(self, other: float, /) -> Self: ...
    # / (division)
    def __truediv__(self, other: Self, /) -> FloatScalar: ...
    def __floordiv__(self, other: Self, /) -> FloatScalar: ...


# endregion generic scalars ------------------------------------------------------------


# region concrete data types -----------------------------------------------------------
@runtime_checkable
class BoolScalar[BoolT](ScalarType, Protocol):
    r"""Protocol for boolean scalars.

    Note:
        Crucially, `BooleanScalar` objects must be convertible to `bool` via the `__bool__` method.
        The `__invert__` method is not included, as `~True` is `-2`, which is not a boolean.
    """

    def __eq__(self, other: Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
    def __ne__(self, other: Any, /) -> Self: ...  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...

    # unary operations
    # NOTE: __invert__ disabled, because ~True == -2
    # def __invert__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # # & (and)
    # def __and__(self, other: Self | BoolT | bool, /) -> Self: ...
    # def __rand__(self, other: Self | BoolT | bool, /) -> Self: ...
    # # | (or)
    # def __or__(self, other: Self | BoolT | bool, /) -> Self: ...
    # def __ror__(self, other: Self | BoolT | bool, /) -> Self: ...
    # # ^ (xor)
    # def __xor__(self, other: Self | BoolT | bool, /) -> Self: ...
    # def __rxor__(self, other: Self | BoolT | bool, /) -> Self: ...

    # & (and)
    @overload
    def __and__(self, other: BoolT, /) -> Self: ...
    # @overload
    # def __and__(self, other: bool, /) -> Self: ...
    @overload
    def __and__(self, other: Self, /) -> Self: ...
    @overload
    def __rand__(self, other: BoolT, /) -> Self: ...
    # @overload
    # def __rand__(self, other: bool, /) -> Self: ...
    @overload
    def __rand__(self, other: Self, /) -> Self: ...
    # | (or)
    @overload
    def __or__(self, other: BoolT, /) -> Self: ...
    # @overload
    # def __or__(self, other: bool, /) -> Self: ...
    @overload
    def __or__(self, other: Self, /) -> Self: ...
    @overload
    def __ror__(self, other: BoolT, /) -> Self: ...
    # @overload
    # def __ror__(self, other: bool, /) -> Self: ...
    @overload
    def __ror__(self, other: Self, /) -> Self: ...
    # ^ (xor)
    @overload
    def __xor__(self, other: BoolT, /) -> Self: ...
    # @overload
    # def __xor__(self, other: bool, /) -> Self: ...
    @overload
    def __xor__(self, other: Self, /) -> Self: ...
    @overload
    def __rxor__(self, other: BoolT, /) -> Self: ...
    # @overload
    # def __rxor__(self, other: bool, /) -> Self: ...
    @overload
    def __rxor__(self, other: Self, /) -> Self: ...

    # endregion binary operations-------------------------------------------------------


@runtime_checkable
class IntScalar[IntT](OrderedScalar, Protocol):
    r"""Protocol for integer scalars."""

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __float__(self) -> float: ...

    # unary operations
    def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # # + (addition)
    # def __add__(self, other: Self | IntT | int, /) -> Self: ...
    # def __radd__(self, other: Self | IntT | int, /) -> Self: ...
    # # - (subtraction)
    # def __sub__(self, other: Self | IntT | int, /) -> Self: ...
    # def __rsub__(self, other: Self | IntT | int, /) -> Self: ...
    # # * (multiplication)
    # def __mul__(self, other: Self | IntT | int, /) -> Self: ...
    # def __rmul__(self, other: Self | IntT | int, /) -> Self: ...
    # # // (floor division)
    # def __floordiv__(self, other: Self | IntT | int, /) -> Self: ...
    # def __rfloordiv__(self, other: Self | IntT | int, /) -> Self: ...
    # # / (division)
    # def __truediv__(self, other: Self | IntT | int, /) -> SupportsFloat: ...
    # def __rtruediv__(self, other: Self | IntT | int, /) -> SupportsFloat: ...
    # # ** (power)
    # def __pow__(self, exponent: Self | IntT | int, /) -> Self: ...
    # def __rpow__(self, base: Self | IntT | int, /) -> Self: ...
    # # % (modulo)
    # def __mod__(self, other: Self | IntT | int, /) -> Self: ...
    # def __rmod__(self, other: Self | IntT | int, /) -> Self: ...

    # + (addition)
    @overload
    def __add__(self, other: int, /) -> Self: ...
    @overload
    def __add__(self, other: IntT, /) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: int, /) -> Self: ...
    @overload
    def __radd__(self, other: IntT, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    @overload
    def __sub__(self, other: int, /) -> Self: ...
    @overload
    def __sub__(self, other: IntT, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: int, /) -> Self: ...
    @overload
    def __rsub__(self, other: IntT, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    @overload
    def __mul__(self, other: int, /) -> Self: ...
    @overload
    def __mul__(self, other: IntT, /) -> Self: ...
    @overload
    def __mul__(self, other: Self, /) -> Self: ...
    @overload
    def __rmul__(self, other: int, /) -> Self: ...
    @overload
    def __rmul__(self, other: IntT, /) -> Self: ...
    @overload
    def __rmul__(self, other: Self, /) -> Self: ...
    # // (floor division)
    @overload
    def __floordiv__(self, other: int, /) -> Self: ...
    @overload
    def __floordiv__(self, other: IntT, /) -> Self: ...
    @overload
    def __floordiv__(self, other: Self, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: int, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: IntT, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: Self, /) -> Self: ...
    # / (division)
    @overload
    def __truediv__(self, other: int, /) -> SupportsFloat: ...
    @overload
    def __truediv__(self, other: IntT, /) -> SupportsFloat: ...
    @overload
    def __truediv__(self, other: Self, /) -> SupportsFloat: ...
    @overload
    def __rtruediv__(self, other: int, /) -> SupportsFloat: ...
    @overload
    def __rtruediv__(self, other: IntT, /) -> SupportsFloat: ...
    @overload
    def __rtruediv__(self, other: Self, /) -> SupportsFloat: ...

    # # ** (power)
    # # NOTE: mypy breaks comparing to int.__pow__ (literal overload)
    # @overload
    # def __pow__(self, exponent: int, /) -> Self: ...
    # @overload
    # def __pow__(self, exponent: IntT, /) -> Self: ...
    # @overload
    # def __pow__(self, exponent: Self, /) -> Self: ...
    # @overload
    # def __rpow__(self, base: int, /) -> Self: ...
    # @overload
    # def __rpow__(self, base: IntT, /) -> Self: ...
    # @overload
    # def __rpow__(self, base: Self, /) -> Self: ...
    # # % (modulo)
    # # NOTE: mypy breaks comparing to numpy.int64.__mod__ (bool overload)
    @overload
    def __mod__(self, other: int, /) -> Self: ...
    @overload
    def __mod__(self, other: IntT, /) -> Self: ...
    @overload
    def __mod__(self, other: Self, /) -> Self: ...
    @overload
    def __rmod__(self, other: int, /) -> Self: ...
    @overload
    def __rmod__(self, other: IntT, /) -> Self: ...
    @overload
    def __rmod__(self, other: Self, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class FloatScalar[FloatT](OrderedScalar, Protocol):
    r"""Protocol for floating point scalars."""

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...

    # unary operations
    # abs() (absolute value)
    def __abs__(self) -> Self: ...
    # - (negation)
    def __neg__(self) -> Self: ...
    # + (positive)
    def __pos__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------

    # # FIXME: https://github.com/python/typing/issues/2021
    # #   Because of the current spec, we need overloads instead of simply unions.
    # # + (addition)
    # def __add__(self, other: Self | FloatT | float, /) -> Self: ...
    # def __radd__(self, other: Self | FloatT | float, /) -> Self: ...
    # # - (subtraction)
    # def __sub__(self, other: Self | FloatT | float, /) -> Self: ...
    # def __rsub__(self, other: Self | FloatT | float, /) -> Self: ...
    # # * (multiplication)
    # def __mul__(self, other: Self | FloatT | float, /) -> Self: ...
    # def __rmul__(self, other: Self | FloatT | float, /) -> Self: ...
    # # / (division)
    # def __truediv__(self, other: Self | FloatT | float, /) -> Self: ...
    # def __rtruediv__(self, other: Self | FloatT | float, /) -> Self: ...
    # # ** (power)
    # def __pow__(self, exponent: Self | FloatT | float, /) -> Self: ...
    # def __rpow__(self, base: Self | FloatT | float, /) -> Self: ...
    # # // (floor division)
    # def __floordiv__(self, other: Self | FloatT | float, /) -> Self: ...
    # def __rfloordiv__(self, other: Self | FloatT | float, /) -> Self: ...
    # # % (modulo)
    # def __mod__(self, other: Self | FloatT | float, /) -> Self: ...
    # def __rmod__(self, other: Self | FloatT | float, /) -> Self: ...

    @overload
    def __add__(self, other: float, /) -> Self: ...
    @overload
    def __add__(self, other: FloatT, /) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: float, /) -> Self: ...
    @overload
    def __radd__(self, other: FloatT, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    @overload
    def __sub__(self, other: float, /) -> Self: ...
    @overload
    def __sub__(self, other: FloatT, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: float, /) -> Self: ...
    @overload
    def __rsub__(self, other: FloatT, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    @overload
    def __mul__(self, other: float, /) -> Self: ...
    @overload
    def __mul__(self, other: FloatT, /) -> Self: ...
    @overload
    def __mul__(self, other: Self, /) -> Self: ...
    @overload
    def __rmul__(self, other: float, /) -> Self: ...
    @overload
    def __rmul__(self, other: FloatT, /) -> Self: ...
    @overload
    def __rmul__(self, other: Self, /) -> Self: ...
    # / (division)
    @overload
    def __truediv__(self, other: float, /) -> Self: ...
    @overload
    def __truediv__(self, other: FloatT, /) -> Self: ...
    @overload
    def __truediv__(self, other: Self, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: float, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: FloatT, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: Self, /) -> Self: ...
    # // (floor division)
    @overload
    def __floordiv__(self, other: float, /) -> Self: ...
    @overload
    def __floordiv__(self, other: FloatT, /) -> Self: ...
    @overload
    def __floordiv__(self, other: Self, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: float, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: FloatT, /) -> Self: ...
    @overload
    def __rfloordiv__(self, other: Self, /) -> Self: ...
    # % (modulo)
    @overload
    def __mod__(self, other: float, /) -> Self: ...
    @overload
    def __mod__(self, other: FloatT, /) -> Self: ...
    @overload
    def __mod__(self, other: Self, /) -> Self: ...
    @overload
    def __rmod__(self, other: float, /) -> Self: ...
    @overload
    def __rmod__(self, other: FloatT, /) -> Self: ...
    @overload
    def __rmod__(self, other: Self, /) -> Self: ...

    # ** (power)
    @overload
    def __pow__(self, exponent: FloatT, /) -> Self | ComplexScalar: ...
    @overload
    def __pow__(self, exponent: float, /) -> Self | ComplexScalar: ...
    @overload
    def __pow__(self, exponent: Self, /) -> Self | ComplexScalar: ...
    @overload
    def __rpow__(self, base: FloatT, /) -> Self | ComplexScalar: ...
    @overload
    def __rpow__(self, base: float, /) -> Self | ComplexScalar: ...
    @overload
    def __rpow__(self, base: Self, /) -> Self | ComplexScalar: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class ComplexScalar[ComplexT](ScalarType, Protocol):
    r"""Protocol for complex scalars."""

    # @property
    # def imag(self) -> Self: ...
    # @property
    # def real(self) -> Self: ...

    # conversion to python scalar
    def __bool__(self) -> bool: ...
    def __complex__(self) -> complex: ...

    # unary operations
    def __abs__(self) -> SupportsFloat: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    #   Because of the current spec, we need overloads instead of simply unions.
    # # + (addition)
    # def __add__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # def __radd__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # # - (subtraction)
    # def __sub__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # def __rsub__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # # * (multiplication)
    # def __mul__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # def __rmul__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # # / (division)
    # def __truediv__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # def __rtruediv__(self, other: Self | ComplexT | complex, /) -> Self: ...
    # # ** (power)
    # def __pow__(self, exponent: Self | ComplexT | complex, /) -> Self: ...
    # def __rpow__(self, base: Self | ComplexT | complex, /) -> Self: ...

    # + (addition)
    @overload
    def __add__(self, other: complex, /) -> Self: ...
    @overload
    def __add__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: complex, /) -> Self: ...
    @overload
    def __radd__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    @overload
    def __sub__(self, other: complex, /) -> Self: ...
    @overload
    def __sub__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: complex, /) -> Self: ...
    @overload
    def __rsub__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    @overload
    def __mul__(self, other: complex, /) -> Self: ...
    @overload
    def __mul__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __mul__(self, other: Self, /) -> Self: ...
    @overload
    def __rmul__(self, other: complex, /) -> Self: ...
    @overload
    def __rmul__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __rmul__(self, other: Self, /) -> Self: ...
    # / (division)
    @overload
    def __truediv__(self, other: complex, /) -> Self: ...
    @overload
    def __truediv__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __truediv__(self, other: Self, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: complex, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: ComplexT, /) -> Self: ...
    @overload
    def __rtruediv__(self, other: Self, /) -> Self: ...
    # ** (power)
    @overload
    def __pow__(self, exponent: complex, /) -> Self: ...
    @overload
    def __pow__(self, exponent: ComplexT, /) -> Self: ...
    @overload
    def __pow__(self, exponent: Self, /) -> Self: ...
    @overload
    def __rpow__(self, base: complex, /) -> Self: ...
    @overload
    def __rpow__(self, base: ComplexT, /) -> Self: ...
    @overload
    def __rpow__(self, base: Self, /) -> Self: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class SpanLikeScalar[SpanT](OrderedScalar[SpanT], Protocol):
    r"""Time delta provides several arithmetical operations."""

    # unary operations
    def __abs__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __neg__(self) -> Self: ...

    # region binary operations ---------------------------------------------------------
    # FIXME: https://github.com/python/typing/issues/2021
    # # + (addition)
    # def __add__(self, other: Self | SpanT, /) -> Self: ...
    # def __radd__(self, other: Self | SpanT, /) -> Self: ...
    # # - (subtraction)
    # # FIXME: broken with numpy. https://github.com/numpy/numpy/issues/28257
    # def __sub__(self, other: Self | SpanT, /) -> Self: ...
    # def __rsub__(self, other: Self | SpanT, /) -> Self: ...
    # + (addition)
    @overload
    def __add__(self, other: SpanT, /) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __radd__(self, other: SpanT, /) -> Self: ...
    @overload
    def __radd__(self, other: Self, /) -> Self: ...
    # - (subtraction)
    @overload
    def __sub__(self, other: SpanT, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> Self: ...
    @overload
    def __rsub__(self, other: SpanT, /) -> Self: ...
    @overload
    def __rsub__(self, other: Self, /) -> Self: ...
    # * (multiplication)
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...

    # / (division)
    # NOTE: plain builtins.int only supports (int, int) -> float
    #   therefore, annotate overload with Self | SupportsFloat
    # NOTE: due to datetime.timedelta, this overload order is forced.
    @overload
    def __truediv__(self, other: SpanT, /) -> FloatScalar: ...
    @overload
    def __truediv__(self, other: Self, /) -> FloatScalar: ...
    # def __truediv__(self, other: Self | SpanT, /) -> SupportsFloat: ...
    # // (floor division)
    # NOTE: There's a historical wart in python: (float // float) -> float
    #   because of this, we must annotate the return as IntScalar | FloatScalar
    @overload
    def __floordiv__(self, other: SpanT, /) -> IntScalar | FloatScalar: ...
    @overload
    def __floordiv__(self, other: Self, /) -> IntScalar | FloatScalar: ...
    @overload
    def __floordiv__(self, other: int, /) -> Self: ...
    # % (modulo)
    def __mod__(self, other: Self, /) -> Self | Any: ...

    # # divmod
    # def __divmod__(self, other: Self, /) -> tuple[IntScalar | FloatScalar, Self]: ...

    # endregion binary operations ------------------------------------------------------


@runtime_checkable
class TimedeltaScalar[SpanT](
    SpanLikeScalar[SpanT | timedelta],
    Protocol,
):
    r"""Protocol for datetime.timedelta compatible scalars."""


@runtime_checkable
class TimeLikeScalar[
    TimeT,  # contra, The compatible time type(s)
    SpanT = Any,  # contra, The compatible span type(s)
    DualT: SpanLikeScalar = Any,  # invariant, The concrete dual type.
](
    OrderedScalar[TimeT],
    Protocol,
):
    r"""TimeStamps can be compared and subtracted."""

    @overload
    def __add__(self, other: SpanT, /) -> Self: ...
    @overload
    def __add__(self, other: DualT, /) -> Self: ...

    @overload
    def __radd__(self, other: SpanT, /) -> Self: ...
    @overload
    def __radd__(self, other: DualT, /) -> Self: ...

    # def __add__(self, other: DualT | SpanT, /) -> Self: ...
    # def __radd__(self, other: DualT | SpanT, /) -> Self: ...

    # __add__ = _TimeLikeAdd[SpanT, DualT]
    # __radd__ = _TimeLikeAddR[SpanT, DualT]
    # __sub__ = _TimeLikeSub[TimeT, SpanT, DualT]

    # FIXME: broken with numpy. https://github.com/numpy/numpy/issues/28257
    @overload
    def __sub__(self, other: SpanT, /) -> Self: ...
    @overload
    def __sub__(self, other: TimeT, /) -> DualT: ...
    @overload
    def __sub__(self, other: DualT, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> DualT: ...

    # @overload
    # def __sub__(self, other: SpanT, /) -> Self: ...
    # @overload

    # @overload
    # def __sub__(self, other: TimeT, /) -> DualT: ...
    # @overload
    # def __sub__(self, other: Self, /) -> DualT: ...
    # @overload
    # def __sub__(self, other: SpanT, /) -> Self: ...
    # @overload
    # def __sub__(self, other: DualT, /) -> Self: ...

    # FIXME: __rsub__ missing on fallback pydatetime
    # @overload
    # def __rsub__(self, other: Self, /) -> TD: ...
    # @overload
    # def __rsub__(self, other: TD, /) -> Self: ...


@runtime_checkable
class DatetimeScalar[
    TimeT,
    SpanT = Any,
    DualT: SpanLikeScalar = Any,
](
    TimeLikeScalar[TimeT | datetime, SpanT | timedelta, DualT],
    Protocol,
):
    r"""Protocol for datetime-like scalars."""


# endregion concrete data types --------------------------------------------------------
